# -*- coding: utf-8 -*-
"""01a_Intro_to_DataFrame.ipynb

Automatically generated by Colab.

## Import the Pandas library

With every new session, import Pandas to use it in your notebook.

The community agreed on using the alias `pd` for Pandas, so we will go with the convention.
"""

import pandas as pd

"""## 1. Creating a DataFrame

### 1.1 Creating an empty DataFrame

Sometimes we need an empty DataFrame: a named space where we can put some data later.
"""

df = pd.DataFrame() # notice the capitalization: pd.dataframe() will result in an error
print(df)

"""We can also specify which columns our DataFrame will have, but still leave the values empty."""

df = pd.DataFrame(columns=['Name', 'Age'])
print(df)

"""### 1.2. Creating a DataFrame from list of lists

One way to fill in a DataFrame upon creation is to use a list of lists. In this case, each *inner* list will become a *row* of the DataFrame. It is therefore important to ensure when using this method that each inner list has the same *length*.

If you don't specify the `columns` parameter, they will default to integers starting from 0.
"""

data = [['Alice', 25], ['Bob', 32], [28, 'Charlie', 'Berlin']]

df = pd.DataFrame(data, columns=['Name', 'Age','City'])

df

df.info()

"""### 1.3. Creating a DataFrame from a dictionary

When using a dictionary to create a DataFrame, each key-value pair will create a *column* of the DataFrame: the *key* will become the label for that column and the *values* will become the values of that column. Again, each collection of *values* in the dictionary will need to have the same *length*.
"""

data = {'Name': ['Alice', 'Bob', 'Charlie'],'Age': [25, 32, 28]}

df = pd.DataFrame(data)
df

"""### 1.4. Creating a DataFrame from .csv file

Depending if you work in Google Colab or in some local IDE (JupyterLab, VScode...), the way to read a .csv file is different. Both will use the same method from the Pandas library, but the way the file's *location* is given will change.

#### 1.4.1. Reading a .csv file from Google Colab

The best way to read a file is to upload it to your Drive. Follow the steps below to read it:

"""

url = 'https://drive.google.com/file/d/18zYGrzRhn_mz1HJLXxSO_MwR0_nWBS3K/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
df = pd.read_csv(path)

"""> ⚠️ **Don't change `path`**: For every new .csv file, you only need to change `url`. You can, of course, change the name of the variable `df` to something suitable as well.

#### 1.4.2. Reading a file from a JupyterLab or VS code

The file is located using the file system on your machine. This is also referred to as a path. One option is to use the *relative path*, which takes as reference where your notebook is located, as in the examples below:
  \
  \
-Folder1  
------notebook.ipynb  
------data.csv  
here the relative path is "data.csv"
  \
  \
-Folder1  
------notebook.ipynb  
------Folder2  
------------data.csv  
here the relative path is "Folder2/data.csv"
  \
 \
-Folder0  
------Folder1  
------------data.csv  
------Folder2  
------------notebook.ipynb  
here the relative path is "../Folder1/<wbr>data.csv"

The ".." in the last example means *go to the folder which contains this folder*. Starting from "Folder2" where the notebook is located, we travel first to the *parent directory* "Folder0", then locate "Folder1" inside it, followed by "data.csv" within that.

We can also use an *absolute path*, which can be useful if the data is stored somewhere not very close to the notebook being used. Such a path might look like: "C:/Desktop/data.csv"
"""

# this will not work in google colab so we will keep it commented

# notice that the file name is contained in quotes: it is a string
# df = pd.read_csv("data.csv")

"""> For other options, check this [file](https://colab.research.google.com/notebooks/io.ipynb).

## 2. Exploration
When you get new data, the first step is to explore and get an overview of the data.  
There are many methods and attributes of pandas `DataFrame` and `Series` that can help you with this task.

> **Reminder**:      
*methods* are built-in functions for data-classes. They are always called with parentheses () at the end, in which *arguments* can (or need to be) placed.      
>
> *attributes* are like sub-variables attached to a variable. They are called without parentheses.   
>
> It is normal to not remember at first if parentheses are needed or not when using these tools. Take notes, check notebooks or documentation; it comes with time.

##### 2.1. [**.info()**](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html)
Use this method to review a concise summary of `df`:
"""

# .info() is a method, and so requires parentheses
df.info()

"""##### 2.2. [**shape**](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shape.html)
Use this attribute to see how many columns and rows `df` has:
"""

# .shape is an attribute, and thus is called without parentheses
df.shape

"""Since `df.shape` is a tuple, you can call its individual elements by their indexes."""

df.shape[0] # number of rows

df.shape[1] # number of columns

"""##### 2.3.  [**describe()**](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html)
Use this method to see certain statistics about `df`'s numeric columns:
"""

# .describe() is another method, and parentheses are needed
df.describe()

"""##### 2.4.  [**.head()**](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html) and [**.tail()**](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html)
Use these methods to see the first or last rows, respectively, of `df`:
"""

df.head()   # without an argument, 5 rows will be returned

df.tail()

# here we see .head() with an argument to specify its behaviour
df.head(10)

df.sample(10)

"""##### 2.5 [**\.columns**](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html)
Use this attribute to see or rename (all of) `df`'s columns:
"""

df.columns

"""##### 2.6 [**\.index**](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.index.html)
This attribute is like `.columns`, but orients instead on rows:
"""

df.index

"""##### 2.7 [**\.isnull()**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isnull.html)
This method creates a `DataFrame` of
- `True` where the value is "missing" (`None` or `np.NaN`)
- `False` where the value is "not missing"
"""

df.isnull()

"""Since a DataFrame of `False` and `True` values is not the most convinient way to check for null values, we can use the `.sum()` method to count up all the `True` values. Since each missing (also called *null*) value returns as `True` (which evaluates as `1` to `False`'s `0`), the sum will effectively count the number of null values in a column."""

df.isnull().sum()

"""This tells us that there are no null values in `df`.

#### 2.8 Selecting a column

Often you need to see just one column of a DataFrame. To do this, use square brackets `[ ]` around the name of that column.
"""

df['Make']

df['Year']

"""You may notice that this looks very different from `df`. This is because each column is itself a `Series`.

## 3. Series
Individual rows or columns of a DataFrame are `Series`. Series objects maintain the indexes of a DataFrame (row numbers for one column, or column names for one row). `Series` can also be constructed independently to store one-dimensional data with indexes.

Here you can check the official Pandas documentation on [Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html).
"""

s = df['Make']

s

"""`Series` and `DataFrame` share almost all the same methods. This is because many DataFrame methods are built on top of Series methods."""

s.head()

s.tail()

"""They also have a lot of same attributes"""

s.index

s.shape

"""#### .name
One attribute unique to Series is `.name`. When taken from a `DataFrame`, the `.name` of a `Series` will be the *label* (column name or row index) of the data taken.
"""

# remember, s was created from the column 'Make' in the dataframe df
s.name

"""## 4. Challenges

#### 4.1
You are given a dictionary containing information about fruits. Create a DataFrame from this dictionary and display it.
"""

fruit_data = {
    'Fruit': ['Apple', 'Banana', 'Orange', 'Grapes'],
    'Color': ['Red', 'Yellow', 'Orange', 'Purple'],
    'Taste': ['Sweet', 'Sweet', 'Sweet', 'Sweet'],
    'Price': [1.0, 0.5, 0.8, 2.5]
}

# Your code here

"""#### 4.2.
You are given a list of lists containing information about cities. Each inner list represents the data for a single city: the city's **name**, **population**, and **country**.     
Create a DataFrame from this list of lists and display the result.
"""

city_data = [
    ['New York', 8175133, 'USA'],
    ['Tokyo', 13929286, 'Japan'],
    ['London', 8908081, 'UK'],
    ['Mumbai', 12442373, 'India']
]

# Your code here

"""#### 4.3
Download the .csv file from this [link](https://github.com/mwaskom/seaborn-data/blob/master/penguins.csv).   
Save the .csv file on your Google Drive.  
Following the instructions from section 1.4 of this notebook, create a DataFrame with this data.
"""

# Your code here

"""#### 4.4
Explore the DataFrame and Series (any column you wish) from the previous exercise using all the methods and attributes learned in this notebook (info, shape, describe, head, tail, columns, index).
"""

# Your code here

"""#### 4.5. Learn more about DataFrame
Try some of the other DataFrame methods and attributes like: \
 \

.dtypes: Attribute to display data types of each column.   
.sample(): Method to obtain a random sample of `n` rows, default `1`.  
.nunique(): Method to count the number of unique values in *each column*.  
.value_counts(): Method to display the frequency of unique values. Best used on a *single column*.  
.max(): Method to get the maximum value of each column.  
.min(): Method to get the minimum value of each column.  
.mean(): Method to calculate the mean of each *numeric column*.  
.median(): Method to calculate the median of each *numeric column*.  
.std(): Method to calculate the standard deviation of each *numeric column*.  
.isnull(): Method to check for missing values in the DataFrame.  
.notnull(): Method to check for non-missing values in the DataFrame. The boolean inverse of `.isnull()`.  
"""

# your code here

"""#### 4.6 Learn more about Series
Visit the official documentation on [Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html) and try as many attributes and methods you wish.  
There is an LMS page about Pandas documentation, take a look!
"""

# your code here

"""###### Hint"""

# To create a Series, select one column of a DataFrame and save the result

# my_series = df[______]

[1,2,3,4,5]

df[['Year','Make']]
