# -*- coding: utf-8 -*-
"""02b_Selecting_and_indexing_bonus_exercises.ipynb

Automatically generated by Colab.

"""

import pandas as pd

"""Read the csv file from this url:
'https://drive.google.com/file/d/1P2EyVCFAPeJcQ_lAN2W-bjwtbizOeFXE/view?usp=drive_link'

Name it `sets_df`
"""

# your code here

url = 'https://drive.google.com/file/d/1OqXhdmjcjdvdrUgjp6di2fZau8ehgl4b/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
sets_df = pd.read_csv(path)
sets_df

"""#### Exercise 1
Select and display only the `"name"` and `"year"` columns from `sets_df` using `.loc`
"""

# your code here

sets_df.loc[:,["name","year"]]

"""#### Exercise 2
Display the first 5 rows and first 3 columns of `sets_df` using `.iloc`
"""

# your code here

sets_df.iloc[:5,:3]

"""#### Exercise 3
Set the `set_num` column as an index using `.set_index()`. Make sure the change is done on the original DataFrame.
"""

# your code here

sets_df = sets_df.set_index("set_num")
sets_df

"""#### Exercise 4
Select the lego sets   
\['2250-2', '7324-21', '9509-15', '2824-8', '7324-12', '60024-11']
"""

# your code here

sets_df.loc[['2250-2', '7324-21', '9509-15', '2824-8', '7324-12', '60024-11']]

"""#### Exercise 5
Building on Exercise 4, select only the columns `"num_parts"` and `"theme_id"` for these sets.
"""

# your code here

sets_df.loc[['2250-2', '7324-21', '9509-15', '2824-8', '7324-12', '60024-11'], ["num_parts","theme_id"]]

"""#### Exercise 6
Reset the index so that `"num_set"` is just a regular column again.
"""

# your code here

sets_df = sets_df.reset_index("set_num")

"""#### Exercise 7
Now set `"year"` as the index and use `.loc` to select the year 1992. What happens?     
Reset the index after.
"""

# your code here

sets_df = sets_df.set_index("year")
sets_df.loc[1992]
sets_df = sets_df.reset_index("year")

"""#### Exercise 8
Use `set_index` to create a DataFrame with [two indexes](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html).
"""

# your code here

sets_df = sets_df.set_index(["year","set_num"])


sets_df = sets_df.reset_index(["year","set_num"])

"""#### Exercise 9
Display the columns `set_num`, `theme_id` and `num_parts` of the last 15 rows by using `.iloc`
"""

# your code here
sets_df
sets_df.iloc[-15:,[1,3,4]]
