# -*- coding: utf-8 -*-
"""03a_Conditional_selecting_and_filtering.ipynb

Automatically generated by Colab.

"""

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Claire', 'David', 'Emma'],
    'Age': [25, 30, 22, 28, 35],
    'Salary USD': [50000, 60000, 45000, 70000, 80000],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing'],
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female']
}

df = pd.DataFrame(data)

df

"""## Preliminary exploration
Before deciding to look into a particular department or age group, it would be helpful to know things like
- What are the different departments in this DataFrame?
- What's the range of ages in this DataFrame?

### `.unique()`

One way to see the distinct values in a column is to use `.unique()`. For readability, it is best to use this method on columns where you only expect a relatively small number of different values.
"""

df['Department'].unique()

"""### Ranges
For continuous numerical values, it might be more useful to know the range of available values. One way to accomplish this is to use `.max()` and `.min()`. Another could be to use `.describe()`, which provides information about the range as well as the quartiles.
"""

print(df['Age'].min(), df['Age'].max())

df['Age'].describe()

"""## Boolean indexing

Boolean indexing allows you to filter and select data based on specific conditions. The first step is to create a boolean mask (a Series of `True` and `False`). This mask then acts as a sort of filter to return rows that line up with `True` in the Series.

### Single condition

Let's say you want to know about those people in your DataFrame older than 29 years of age.

You can start by formalising the condition:
"""

df['Age'] > 29

"""Comparing the output to 'df', you can see that for every row where the listed age is over 29, the above Series contains the value `True`.

This Series can then be used inside `.loc` to select rows. Since `df` and the Series have the same index, this technique returns all rows aligned to `True` values.
"""

df.loc[df['Age'] > 29,:]

"""Logical conditions can become long and messy for some tasks, so it is sometimes a good practice to save the boolean mask as a separate variable and pass this variable to `.loc`."""

age_mask = df['Age'] > 29

df.loc[age_mask,:]

department_mask = df['Department'] == "IT"

df.loc[department_mask,:]

"""### Multiple conditions

Conditions can be combined using logical operators:
* **|** for OR,
* **&** for AND
* **~** for NOT.

When typing conditions in full, these must be grouped by using parentheses. Named variables, on the other hand, need not be enclosed.

On a mac:

`~` `option` + `N`

`|` `option` + `7`
"""

df.loc[ (df['Age'] > 29) & (df['Department']== "IT") , :]

df.loc[age_mask & department_mask, :]

"""## Pandas filtering methods

Pandas also provides several methods which return boolean masks, and thus can be used in combination with `.loc` to filter DataFrames.

### .isin()
Used to compare a Series or DataFrame against a given collection, this method will return `True` for each value compared if the value is contained in the collection.     
We will most often use this to compare a single column (Series) of a DataFrame to a given list.
"""

df['Name'].isin(["Alice","David"])

alice_david_mask = df['Name'].isin(["Alice","David"])

df.loc[alice_david_mask,:]

"""### .between()
Used to evaluate a Series, `.between()` returns `True` on any row whose value lies in the range of the two given arguments.        
By default, results will be inclusive of the two boundary values.
"""

df['Age'].between(25,30)

df.loc[df['Age'].between(25,30),:]

df.loc[df['Name'].between("Bella","Daniel"),:]

"""### .nlargest() and .nsmallest()
Capable of filtering and sorting all at once, these methods return the `n` rows containing the largest or smallest values in a specified column or columns.
"""

df.nlargest(3,columns="Salary USD")

df.nsmallest(5,columns="Age")

"""# Challenges"""

data = {
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco','London', 'Boston'],
    'Population': [8622698, 3990456, 2716000, 2312717, 870887, 8982000, 675647],
    'Area_sq_miles': [302.6, 468.7, 227.3, 627.8, 46.9, 607.0, 89.6],
    'Country': ['USA', 'USA', 'USA', 'USA', 'USA', 'UK', 'USA'],
    'Year_Founded': [1624, 1781, 1833, 1836, 1776, 43, 1625]
}
cities_df = pd.DataFrame(data)
cities_df

"""### Challenge 1
Select all cities with a population greater than 2 million.

"""

# Your code here

pop_mask = cities_df['Population'] > 2000000
pop_mask

"""### Challenge 2
Select the 'City' and 'Area_sq_miles' columns for cities with an area greater than 300 square miles.

"""

# Your code here

city_area_mask = cities_df['Area_sq_miles'] > 300
city_area_mask

cities_df.loc[city_area_mask, 'City']

"""### Challenge 3
Select the 'City', 'Area_sq_miles', and 'Year_Founded' columns for cities with a population less than 1 million or an area less than 500 square miles.

"""

# Your code here

pop_mask = cities_df['Population'] < 1000000
area_mask = cities_df['Area_sq_miles'] < 500
cities_df.loc[pop_mask | area_mask, ['City','Area_sq_miles', 'Year_Founded']]

"""### Challenge 4
Using `.nlargest()`, select the 'City', 'Population', and 'Area_sq_miles' columns for the top 3 largest cities by population.

"""

# Your code here

cities_df.nlargest(3, 'Population')[['Population', 'City',  'Area_sq_miles']]

"""### Challenge 5
Using `.isin()`, select the 'City', 'Population', and 'Year_Founded' columns for the cities San Francisco and Boston.
"""

# Your code here

column = ['City', 'Population', 'Year_Founded']
cities_df.loc[cities_df['City'].isin(['San Francisco', 'Boston']),column]

"""### Challenge 6
Select the 3 cities with smallest populations.
"""

# Your code here

cities_df.nsmallest(3, 'Population')[['Population']]

"""### Challenge 7
Using the ~ operator, select the 'City', 'Country', 'Population', and 'Area_sq_miles' columns for cities located outside the USA.
"""

# Your code here

usa = ['City','Country','Population','Area_sq_miles']
cities_df.loc[~(cities_df['Country'] == 'USA'),usa]

"""# Bonus
## A note on method chaining and a different way to filter

`.query()` allows you to filter data using a logical expression as a string. Since this method does not require column names to take reference to `df`, complex conditions can be written more easily. On the other hand, referencing strings within strings requires careful attention to the mixing of double and single quotes.
"""

df.query("Department == 'IT'")

df.query("Department == 'IT' & Age > 29")

"""Because `.query()` does not require you to refer to a DataFrame by name, it can be used in-line with other methods which transform or select data.

As an example, we can select the four youngest employees and then filter for those making a certain salary:
"""

df.nsmallest(4, 'Age').query('Department == "IT"')

"""Since the argument of `.query()` is itself a string, there are some special cases you might consider:  
1. When refering to a column that has a whitespace in the name, enclose the column with a backtick (`)
2. When refering to variables, prefix the variable with @
"""

df.query(" `Salary USD` < 50000")

age_limit = 25

df.query("Age > @age_limit")

"""### Challenge 8
Using `.query()`, select all cities with a population greater than 2 million and founded after the year 1800.

"""

# Your code here

cities_df.query('(Population > 2000000) & (Year_Founded > 1800)')
cities_df

"""### Challenge 9
Using `.query()`, select all cities with an area between 100 and 300 square miles.

"""

# Your code here

cities_df.query('(Area_sq_miles.between(100,300))')
cities_df
