# -*- coding: utf-8 -*-
"""04_Debugging_challenges.ipynb

Automatically generated by Colab.

# Python Debugging Exercises 🐞
Welcome! In each exercise below, you'll find some buggy Python code. 🐛 Your mission is to fix the error and get the code running. We give hints to help you along the way! 😊

---
## Exercise 1
The code is trying to print a greeting, but there's a bug 🐛 in the `print` statement.
"""

print("Hello, world!")

"""---
## Exercise 2
We have a variable `message`, but I can't print it. Uh oh!
"""

message = "Hi there!"
print(message)

"""---
## Exercise 3
Our `print` statement is having problems again. Can you find what's wrong here?
"""

if True:
  print("Oh no!")

"""---
## Exercise 4
If only this would work!
"""

if 5 > 3:
    print("5 is greater than 3")

"""---
## Exercise 5
Why won't this code print out my age?
"""

age = 30
print("I am " + age + " years old")

print("I am ", age , " years old")

"""---
## Exercise 6
I'd like to print out the `cherry`, why won't the code let me?

"""

fruits = ["apple", "banana", "cherry"]
print(fruits[2])

"""---
## Exercise 7
Why can't `int()` turn `ten` into an integer? Can it convert stings to integers?
"""

number = int(10)
number

"""---
## Exercise 8
What's wrong with the loop?
"""

for i in range(3):
    print(i)

"""---
## Exercise 9
A string isn't recognised? What's up?
"""

print("Hello")

"""---
## Exercise 10
Is it possible to multiply a string? If so, how?
"""

sound = "ha"
print(sound * 3) #it cannot multiply to a float but only integer

"""---
## Exercise 11
What's wrong with this loop?
"""

for i in range(5):
    print(i)

"""---
## Exercise 12
Why can't the list be printed?
"""

items = [1, 2, 3]
print(items)

"""---
## Exercise 13
Why won't this code print out the 5th letter of `hello`?

"""

s = "hello"
print(s[4])

"""---
## Exercise 14
Why can't `4` be added to the list? Can you add `4` to the list in `print()`?
"""

nums = [1, 2, 3]
print(nums + [4])

"""---
## Exercise 15
Nothing plus 5 is surely 5. Is it possible to save this code?
"""

value = None
print(value + 5)

print((value or 0) + 5)

