# -*- coding: utf-8 -*-
"""05a_Cleaning_and_updating_data.ipynb

Automatically generated by Colab.

## Import the Pandas library and create DataFrame

Before doing anything else, you'll need to import Pandas and get some data to work with.
"""

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Claire', 'David', 'Emma','Emma'],
    'Age': [25, 30, 22, None, 35,35],
    'Salary': ['50000', '60000', '45000€', '70000', '80000', '80000'],
    'Department': ['HR', None, 'Finance', 'IT', 'Marketing', 'Marketing'],
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female', 'Female'],
    'Hire_Date': ['2020-03-15', '2019-05-20', '2021-01-10', '2018-11-05', '2022-02-28', '2022-02-28'],
    'Performance_Rating': ['4.5', '3.8', None, '4.0', '4.7', '4.7'],
    'ID':['1.5','1.6','1.7','1.8','1.9','1.9']
}

df = pd.DataFrame(data)
df

"""## 1. Dealing with missing values

Missing values, also known as null values, can be a headache when handling data. They might cause errors, or throw off counts.

### .dropna()
One strategy to deal with missing values is to simply eliminate them. `.dropna()` will delete either rows or columns containing missing values.

> **Axis:** Several Pandas methods contain a parameter called 'axis'. This parameter determines in which direction the function will be applied.  
`axis=0` applies along rows  
`axis=1` applies along columns
"""

df.dropna(axis=0)   # to drop rows

"""Each row containing at least one missing value (None or NaN) has been removed from the output."""

df.dropna(axis=1)   # to drop columns

"""This time, all columns containing at least one missing value have been dropped.

### .fillna()
Another method is to fill in missing values. These can be inferred from other values in the row or column, or set to a constant.   
Let's take the mean of everyones age and use that value to fill in any missing data in the column.
"""

age_mean = df['Age'].mean()
age_mean

df['Age'] # here we see one missing age

df['Age'].fillna(age_mean)

"""## 2. Handling duplicates

Duplicates can throw off an analysis. They might make it seem as if more sales were made or more customers exist than is actually true.

### .drop_duplicates()
Look closely at the last two lines of `df`. They contain all of the same information! `.drop_duplicates()` exists to spot such repeats and get rid of them in one easy step.
"""

df

df.drop_duplicates()

"""What if we had actually hired two people named Emma to the marketing department on the same day?
    
`.drop_duplicates()` can also target a *single column* for repeated information by using the `subset=` parameter. In this way, items that should be unique — such as "ID" — can be used to determine which rows should be dropped.
"""

df.drop_duplicates(subset="ID")

"""## 3. Data types conversions

To perform certain operations, data must have the right type. There is no way to find the median of a collection of strings, only of floats or integers.    
In Pandas, the data type of a Series or value is known as its "dtype".

### .astype()
By entering the desired dtype as a parameter, this method can change a Series, or even an entire DataFrame. This is also known as "casting".
"""

df['Performance_Rating'].astype('float')

"""### pd.to_numeric()
A bit more robust than `.astype()`, `pd.to_numeric()` is able to handle non-convertable values by returning nulls.

> **Note:** Unlike the other techniques seen so far in this notebook, this one is not a method attached to `DataFrame` or `Series`. Instead, it is a function contained in the Pandas library. This is why it is called with `pd` in front, rather than `df` or `df['column']`.
"""

pd.to_numeric(df['Salary'], errors='coerce')

"""## 4. Combining

You may wish sometimes to turn two DataFrames into one. This can be especially helpful when extracting data from multipe sources but analysing it all together.

### pd.concat()
Another *function* in the Pandas library, `pd.concat()` combines DataFrames one-atop-the-other or side-by-side. Alignments are made on the labels of the specified axis.
"""

skills_data = {
     'Name': ['Alice', 'Bob', 'Claire', 'David', 'Emma', 'Emma'],
    'Skills': ['Python', 'Java', 'SQL', 'Python, C++', 'R, Excel', 'R, Excel']
}
skills_df = pd.DataFrame(skills_data)
skills_df

pd.concat([df,skills_df['Skills']], axis=1)

"""A few things to notice above:
- The DataFrames are passed to `pd.concat()` *as a list*
- Only one column of `skills_df` appears, because only that column was called with the indexing operator
- `axis=1` controls the *direction* of concatenation; remember `1` in terms of Pandas axes means column-wise
"""

new_people_data = {
    'Name': ['Grace', 'Henry'],
    'Age': [29, 31],
    'Salary': [60000, 68000],
    'Department': ['Marketing', 'IT'],
    'Gender': ['Female', 'Male'],
    'Hire_Date': ['2023-08-10', '2023-08-15'],
    'Performance_Rating': [4.5, 4.2],
    'ID':['2.0','2.1']
}
new_people_df = pd.DataFrame(new_people_data)
new_people_df

pd.concat([df, new_people_df], axis=0, ignore_index=True)

"""This time, by using `axis=0`, new *rows* are added to `df`.    
`ignore_index=True` stops the indexes in `new_people_df` from carrying over. Otherwise, the resulting index would have been      
`[0, 1, 2, 3, 4, 5, 0, 1]`

## Sorting

### .sort_values()
As you might guess, `.sort_values()` will sort the given column(s) numerically or alphabetically. By default, results will be sorted in ascending order and null values will be sorted last.
"""

df.sort_values('Age')

df.sort_values('Age', ascending=False)

"""## Save the change!!"""

df

"""⚠️ Notice that not a single change has actually been made to `df` — there are still duplicates and missing values, and neither skills nor new people have been added.  

In each case, the outputs of the above techniques need to be *explicitly assigned* in order to remain. In other words, to "change" `df` you need to overwrite it with one of the *new* outputs you've seen.
"""

df = df.drop_duplicates().copy()
df['Performance_Rating'] = df['Performance_Rating'].astype(float)
df

"""> **Note:** In general, if you enter some code and a DataFrame appears on your screen, this is a *new object* and would need to be assigned under the same name to "alter the original".
>
> Sometimes, however, what appears on the screen is not new (a 'copy'), but only a view of an object (a 'slice'). In those cases, it is important to save a *copy of the slice* via `.copy()`, as above.

## 5. Dropping and creating columns

There are times when a DataFrame contains data which is not needed. At other times, it needs additional information.

### .drop()
Used to eliminate rows or columns according to their label(s). Again, `axis`makes an appearance to specify in which direction to operate.
"""

df.drop('ID',axis=1)

df.drop(4,axis=0)

"""### Create a column
You can create a new column by simply assigning it a value.
"""

df['new_column'] = 'some_value'
df

"""A new column can also be a derived from one or more existing columns."""

df.loc[:, 'another_column'] = df['Gender'] + ' ' + df['Department']
df

"""## 5. Conditional updating

There are times when values need to be updated, but only if they meet certain criteria.

### Using `.loc`
Since `.loc` allows you to filter conditionally, it is already well suited to updating values via assignment.    
`df.loc[condition, column] = new_value`

Someone has noticed that Claire's age was entered incorrectly! Let's correct it:
"""

name_mask = df['Name'] == "Claire"
df.loc[name_mask,['Age']]

"""In this first step, we are able to view Claire's age. A new value can be assigned via `=`."""

df.loc[name_mask,['Age']] = 27
df

"""Several values meeting the same condition can also be updated at the same time.    
Let's change the 'Marketing' department to 'Public Relations'.
"""

marketing_mask = df['Department'] == "Marketing"
df.loc[marketing_mask, 'Department'] = "Public Relations"
df

"""It is also possible to use multiple conditions when filtering and updating data.     
Let's give everyone a raise who is under 29 and works in Finance or HR.
"""

age_mask = df['Age'] < 29
department_mask = df['Department'].isin(['Finance', 'HR'])

df.loc[age_mask & department_mask, "Salary"] = 55000
df

"""> **Note:** One reason to assign new values with `.loc` is that it always updates the original DataFrame. Other methods may modify only a copy of the data, leading to unpredictable outcomes or lost work.

### .where()
Sometimes instead of looking to *meet* a condition, you may wish to update values that *fail to meet* your criteria.
"""

df

"""Let's check our employees' performance ratings and give a salary of only 30000 to anyone doing worse than a 4:"""

df['Salary'].where(df['Performance_Rating'] >= 4, 30000)

"""This is functionally equivalent to writing     
`df.loc[~(df['Performance_Rating'] >= 4), 'Salary'] = 30000`      
except that `.where()` requires you to explicitly *save* the result, whereas assignment is already written in with `.loc`.
"""

example_df = df.copy()
example_df.loc[~(example_df['Performance_Rating'] >= 4), 'Salary'] = 30000
example_df['Salary']

"""Since the logic of changing a value where a condition is *not met* might feel a bit strange, you can always flip the logic by negating the condition with `~`."""

df['Salary'].where(~(df['Performance_Rating'] < 4), 30000)

"""> ⚠️ **Watch out for null values!**
>
> Null values have certain behaviour characteristics that need to be accounted for when updating values conditionally:
- Equality comparisons of all sorts evaluate to `False` *except*
- Non-equality comparisons (`!=`) evaluate to `True`
- Negation with `~` will then flip **either** of the above results   
>  
> Notice how the salary in row 2 is altered by using `.where()` and `.loc[~ ]`, but is **not altered** when using `.where(~ )`.

### .replace()
Offering even more options and flexibility, `.replace()` is capable of updating values across multiple columns and assigning different results to different matches, as well as handling more advanced "pattern matching".

Imagine all our departments changed their names to something else. Instead of writing as many conditions as there are replacements, we can use `.replace()` in a variety of ways. Here is an example using a dictionary:
"""

replace_dict = {'HR': 'Human Resources',
                'Finance':'Accounting',
                'IT':'Tech',
                'Public Relations':'Marketing'}

df.replace(replace_dict)

"""You can direct the changes to a single column as well:"""

df['Department'].replace(replace_dict)

"""Pattern matching can be useful when trying to replace information in multiple columns with slightly differing values. This is done with the argument `regex=True`. Notice the code below changes values in both Department and `another_column`."""

replace_dict = {'HR': 'Human Resources',
                'Finance':'Accounting',
                'IT':'Tech',
                'Public Relations':'Marketing'}
df.replace(replace_dict, regex=True)

"""## Challenges"""

data = {
    'City': ['New York', 'New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco', 'London', 'Paris', 'Tokyo', 'Sydney', 'Toronto'],
    'Population': [8622698, 8622698, 3990456, None, 2312717, 870887, 8982000, 2140526, None, '2079700', 2930000],
    'Area_sq_miles': [302.6, 302.6, 468.7, 227.3, 627.8, 46.9, 607, None, 845.8, 2058.4, 630.2],
    'Country': ['USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'United Kingdom', 'France', 'Japan', 'Australia', 'Canada'],
    'Year_Founded': [1624, 1624, 1781, 1833, 1836, None, 43, 52, 660, 1788, None]
}

cities_df = pd.DataFrame(data)

cities_df

"""### Challenge 1
Convert the 'Population' column to numeric

"""

# Your code here

cities_df['Population'] = pd.to_numeric(cities_df['Population'], errors='coerce')
cities_df

"""### Challenge 2
Fill missing area values with the median area


"""

# Your code here
area_median = cities_df['Area_sq_miles'].median()
area_median
cities_df.loc[:, 'Area_sq_miles'] = cities_df['Area_sq_miles'].fillna(area_median)
cities_df

"""### Challenge 3
Remove duplicates from the DataFrame

"""

# Your code here

cities_df = cities_df.drop_duplicates().copy()
cities_df

"""### Challenge 4
Fill missing population values with the mean population

"""

# Your code here

population_mean = cities_df['Population'].mean()
cities_df.loc[:, 'Population'] = cities_df['Population'].fillna(population_mean)
cities_df

"""### Challenge 5
Update the 'Year_Founded' to 1800 for cities with missing year values
"""

# Your code here

cities_df.loc[:, 'Year_Founded'] = cities_df['Year_Founded'].fillna(1800)
cities_df

"""### Challenge 6
Update the 'Year_Founded' to 1800 for cities in the USA founded before 1800

"""

# Your code here

before_1800 = cities_df['Year_Founded'] < 1800
in_USA = cities_df['Country'] == 'USA'
cities_df.loc[before_1800 & in_USA, 'Year_Founded'] = 1800
cities_df

"""### Challenge 7
Set the 'Population' to 8 million for cities with a population greater than 8 million
"""

# Your code here

cities_df.loc['Population'] = cities_df['Population'].where(cities_df['Population'] < 8000000, 8000000)
cities_df

"""### Challenge 8
Use .replace() to update 'Country' names 'United Kingdom' to 'UK' and 'Canada' to 'CAN'

"""

# Your code here

cities_df['Country'] = cities_df['Country'].replace({ 'United Kingdom' : 'UK' , 'Canada':'CAN'})
cities_df

"""### Challenge 9
Concatenate 'City' and 'Country' columns into a new 'Location' column

"""

# Your code here

cities_df['Location'] = cities_df['City'] + ', ' + cities_df['Country']
cities_df

"""### Challenge 10
Drop the 'Location' column
"""

# Your code here

cities_df = cities_df.drop('Location', axis=1)
cities_df

"""### Challenge 11
Create a new column 'Size' and assign it a value 'unknown' to all rows

"""

# Your code here

cities_df["Size"] = 'unknown'
cities_df

"""### Challenge 12
Change Size to 'Small' for all cities with 'Area_sq_miles' less than 400.  
Change Size to 'Big' for all cities with 'Area_sq_miles' bigger than 400.
"""

# Your code here
size_mask = cities_df['Area_sq_miles'] < 400
cities_df.loc[size_mask, 'Size' ] = 'Small'
cities_df.loc[~size_mask , 'Size'] = 'Big'
cities_df
