# -*- coding: utf-8 -*-
"""06a_String_methods.ipynb

Automatically generated by Colab.

## Import the Pandas library and create DataFrame

Before doing anything else, you'll need to import Pandas and get some data to work with.
"""

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Claire', 'David', 'Emma'],
    'Age': [25, 30, 22, 28, 26],
    'Department': ['Marketing', 'Finance', 'Sales', 'HR', 'Marketing'],
    'City': ['New York', 'London', 'Paris', 'San Francisco', 'Sydney'],
    'Email': ['alice@example.com', 'bob@example.com', 'claire@example.com', 'david@example.com', 'emma@example.com'],
    'Job_Title' : ['Data Scientist', 'Financial Analyst', 'Sales Executive', 'HR Manager', 'Marketing Specialist'],
    'Full_Name' : ['Alice Johnson', 'Bob Smith', 'Claire Williams', 'David Lee', 'Emma Brown'],
    'Phone' : ['123-456-7890', '987-654-3210', '555-123-4567', '111-222-3333', '444-555-6666'],
    'Address' : ['       123 Main Street', '        456 Park Avenue', '         789 Elm Road', '        321 Oak Street','        555 Maple Lane']
}

df = pd.DataFrame(data)

df

"""## The `.str` accessor

In Pandas, the `.str` accessor allows us to perform various string operations on DataFrame columns containing string values. This provides a convenient and efficient way to work with textual data within DataFrames.

> **Note:** The `.str` accessor works on Series. To use any of the tools below, be sure to specify which column of a DataFrame you wish to work with.

### String indexing and slicing

We can access individual characters of each string in a DataFrame column using string indexing. Let's select the first letter of each name:
"""

df['Name'].str[0]

"""Using a slice in the string indexer, we'll now select the first four characters of each city."""

df['City'].str[:4]

"""### Converting cases

`.str.lower()`      
With this method you can change all letters to lower case.
"""

df['Full_Name'].str.lower()

"""Similarly, Pandas offers:  

`str.upper()`  
Converts all characters to uppercase.  

`str.title()`  
Converts the first character of each word to uppercase and the remaining characters to lowercase.  

`str.capitalize()`  
Converts first character of the whole string to uppercase and the remaining characters to lowercase.  

`str.swapcase()`  
Converts uppercase to lowercase and lowercase to uppercase.  

`str.casefold()`  
Removes all case distinctions in the string. This method is meant to deal with the kind of special characters generally not recognized as having upper and lower cases, e.g. "ß" becomes "ss".

### Conditions

`.str.startswith()` and `.str.endswith()`  
Often used for filtering DataFrames, these methods will check if the first or last character(s) in each string match(es) the given string.
"""

df['Email'].str.startswith('david')

"""`.str.contains()`  
Another useful method for filtering `.str.contains()` checks if any part of each string matches the given string.
"""

df['Email'].str.contains('@')

"""### Length and counting

`.str.len()`  
This method will count and return the number of characters in each string.
"""

df['Address'].str.len()

"""`.str.count()`  
returns the count of occurrences of a specified substring in each string of the column
"""

df['Email'].str.count('example')

"""### Manipulating strings

`.str.replace()`  
Used to locate one sub-string and, if it exists, replace it with another.
"""

df['City'].str.replace('New', 'Old')

"""`.str.strip()`  
It is not uncommon for data to end up carrying certain artefacts of the ETL process, often as leading or tailing characters. Most commonly, this will result in whitespace; `.str.strip()` removes whitespace before and after a string by default, and can remove others when specified.
"""

df['Address']

df['Address'].str.strip()

"""`.str.split()`  
Used to break a string down into its constituent parts, `.str.split()` will search a string for a given character, creating items in a list each time that character is encountered. By default, splits will be made on whitespace.
"""

df['Full_Name'].str.split()

"""The resulting lists can be accessed with a further `.str` followed by an indexer or `.get()`."""

df['Full_Name'].str.split(' ').str[1]

df['Full_Name'].str.split(' ').str.get(1)

"""## Regular expressions

Regular expressions, commonly known as regex, are powerful tools for pattern matching and text manipulation.  
The regex syntax consists of metacharacters, quantifiers, character classes, and more, which define the rules for matching patterns in strings.

Common Metacharacters and Their Meanings:

**. (Period)**: Matches any character except a newline.  
For example, the pattern a.b will match 'aab', 'acb', 'a9b', but not 'a\nb'.

**\* (Asterisk)**: Matches zero or more occurrences of the preceding character.

 For example, the pattern ab*c will match 'ac', 'abc', 'abbc', 'abbbc', and so on.

**\+ (Plus)**: Matches one or more occurrences of the preceding character.

 For example, the pattern ab+c will match 'abc', 'abbc', 'abbbc', but not 'ac'.

**? (Question Mark)**: Matches zero or one occurrence of the preceding character.  
For example, the pattern colou?r will match both 'color' and 'colour'.

**^ (Caret)**: Matches the start of a string.  
For example, the pattern ^abc will match 'abc' only if it appears at the beginning of a string.

**\$ (Dollar)**: Matches the end of a string.  
For example, the pattern abc$ will match 'abc' only if it appears at the end of a string.

**[ ] (Square Brackets)**: Matches any single character within the specified set.  
For example, the pattern [aeiou] will match any vowel.

**[^] (Caret Inside Square Brackets)**: Matches any single character not within the specified set.  
For example, the pattern [^aeiou] will match any non-vowel.

Try [this site](https://regex101.com/) for diving deeper into regular expressions.

### Regex in Pandas
In pandas, certain methods allow for regex pattern matching — some by default and others when explicitly set to do so.
"""

df['Phone'].str.contains(r'\d+-\d+-\d+')

"""`\d+-\d+-\d+`     
This pattern matches all strings that containg two minus signs with 1 or more number characters between them.

## Challenges
"""

data = {
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco', 'London', 'Paris', 'Berlin', 'Rome', 'Tokyo'],
    'Country': ['USA', 'USA', 'USA', 'USA', 'USA', 'UK', 'France', 'Germany', 'Italy', 'Japan'],
    'Population (Millions)': [8.4, 3.9, 2.7, 2.3, 0.9, 8.9, 2.1, 3.7, 2.8, 13.9],
    'Area (km2)': [468.9, 502.8, 227.6, 1, 121.4, 1572, 105.4, 891.8, 1285, 2187],
    'Language': ['English', 'English', 'English', 'English', 'English', 'English', 'French', 'German', 'Italian', 'Japanese'],
    'Currency': ['USD', 'USD', 'USD', 'USD', 'USD', 'GBP', 'EUR', 'EUR', 'EUR', 'JPY'],
    'Continent': ['North America', 'North America', 'North America', 'North America', 'North America', 'Europe', 'Europe', 'Europe', 'Europe', 'Asia'],
    'Is_Capital': [False, False, False, False, False, True, True, True, True, True]
}

cities_df = pd.DataFrame(data)

# Adding more rows
extra_data = {
    'City': ['Sydney', 'Seoul', 'Beijing', 'Moscow', 'Cairo', 'Mumbai'],
    'Country': ['Australia', 'South Korea', 'China', 'Russia', 'Egypt', 'India'],
    'Population (Millions)': [5.3, 9.7, 21.5, 12.5, 9.5, 20.7],
    'Area (km2)': [1687, 605, 16411, 2561, 3034, 603],
    'Language': ['English', 'Korean', 'Mandarin', 'Russian', 'Arabic', 'Hindi'],
    'Currency': ['AUD', 'KRW', 'CNY', 'RUB', 'EGP', 'INR'],
    'Continent': ['Australia', 'Asia', 'Asia', 'Europe', 'Africa', 'Asia'],
    'Is_Capital': [False, True, True, True, True, False]
}

extra_df = pd.DataFrame(extra_data)
cities_df = pd.concat([cities_df, extra_df], ignore_index=True)

cities_df

"""### Challenge 1
Create a new column 'City_Length' that contains the length of each city name
"""

# Your code here

cities_df['City_Length'] = cities_df['City'].str.len()
cities_df

"""### Challenge 2
Convert the 'City' names to uppercase and store them in a new column 'City_Upper'
"""

# Your code here

cities_df['City_Upper'] = cities_df['City'].str.upper()
cities_df

"""### Challenge 3
Check if the 'City' names end with the letter 'o'. Create a new column 'Ends_With_O' with the boolean results
"""

# Your code here

cities_df['Ends_With_O'] = cities_df['City'].str.endswith('o')
cities_df

"""### Challenge 4
Replace the word 'York' in 'City' names with 'Ville' and update the 'City' column accordingly
"""

# Your code here

cities_df = cities_df['City'].str.replace('York', 'Ville')
cities_df

"""### Challenge 5
Create a new column 'Country_Code' by extracting the first three characters from the 'Country' names
"""

# Your code here

cities_df['Country_Code'] = cities_df['Country'].str[:3]
cities_df

"""### Challenge 6
Count the occurrences of the letter 'a' in each 'City' name
"""

# Your code here

cities_df['City'].str.count('a')

"""### Challenge 7
Check if the 'City' names start with the letter 'C' and end with the letter 'o'
"""

# Your code here

cities_df['City'].str.startswith('C') & cities_df['City'].str.endswith('o')

"""### Challenge 8
Check if the 'City' names contain exactly two words
"""

# Your code here

cities_df['City'].str.count(' ') == 1

#cities_df[cities_df['City'].str.split().str.len()==2]

#cities_df["City"].str.contains(r"^\w+\s\w+$")

