# -*- coding: utf-8 -*-
"""07a_Grouping_and_merging.ipynb

Automatically generated by Colab.

## Import the Pandas library and create DataFrame

Before doing anything else, you'll need to import Pandas and get some data to work with.
"""

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Claire', 'David', 'Emma', 'Alice', 'David'],
    'Age': [25, 30, 22, 28, 35, 25, 28],
    'Department': ['IT', 'HR', 'Finance', 'IT', 'Marketing', 'HR', 'IT'],
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male'],
    'Salary': [50000, 60000, 45000, 70000, 80000, 52000, 72000],
    'Rating': [4.5, 3.8, 4.2, 4.0, 4.7, 4.3, 3.9]
}

df = pd.DataFrame(data)
df

"""## 1. Grouping

Working with data, you'll often wish to know less about how every entity looks than how they look in aggregates.
- You can't know *each customer's* favorite time to shop, but you can know when *customers in different age groups* shop most often.
- You may not wish to know how *every product* sells, but rather how *products in different departments* are selling right now.

Grouping data by some feature allows you to collect those entries sharing some common feature and evaluate them collectively.

### 1.1 `.groupby()`

The first step in grouping with Pandas is to choose which feature (i.e. which column) will be be used to determine the groups.
"""

df.groupby("Department")

"""**What is this strange output?**

By itself, `.groupby()` will only lay the groundwork for grouping. To get any useful information, you'll need to specifiy some sort of aggregate: A way to describe many entries at once.

### 1.2 Aggregate functions
From your work with statistics, you will already know several aggregate functions, such as mean, median or standard deviation.  

Pandas provides several built-in functions to summarize data, some of which you'll find listed below. While many methods can be applied to Series or DataFrame as a whole, today we'll how they can be used to describe grouped data.

| Aggregate function | Description                                    |
|---------------------|------------------------------------------------|
| [count()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.count.html)             | Returns count for each group                   |
| [size()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.size.html?highlight=size#pandas.DataFrame.size)             | Returns size for each group                    |
| [sum()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html)               | Returns total sum for each group               |
| [mean() ](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html)              | Returns mean for each group. Same as average() |
| [std()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.std.html)               | Returns standard deviation for each group      |
| [var() ](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.var.html)              | Returns variance for each group                      |
| [describe()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html)          | Returns different descriptive statistics                   |
| [min() ](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.min.html)               | Returns minimum value for each group           |
| [max() ](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.max.html#pandas.DataFrame.max)              | Returns maximum value for each group           |

Applied to a DataFrame, `.mean()` will return the numerical mean of each column. Since this calculation can only be performed on numbers, an error will be returned on DataFrame containing non-numerical values unless `numeric_only=True`.
"""

df.mean(numeric_only=True)

"""The same method can be used on a single Series to get its mean."""

df['Age'].mean()

"""The method `.count()` will simply count the number of non-null entries."""

df['Age'].count()

"""Now let's see what happens if we use `.mean()` after grouping:"""

df.groupby('Department').mean(numeric_only=True)

"""Let's break down what we see here:
- The index has changed. Now each **unique** value from the "Department" column has become an index.
- Each column now represents the mean of that feature *with respect to the __group__*.
- Since only one person works in Finance, we see the same numbers as appear on line 2 of `df`.
- HR has two members — earning 52,000 and 60,000 per year — so the grouped DataFrame shows a mean earning of 56,000 in HR.

#### 1.2.1 Aggregating on one column

To see aggregate data about a single column, you can select that column with the indexing operator after performing the grouping.
"""

df.groupby('Gender')['Age'].mean()

"""#### 1.2.2 Aggregating on two or more columns
Multiple columns can be chosen to perform one aggregate function on by giving a list of column labels to the indexing operator
"""

df.groupby('Gender')[['Age','Salary']].mean()

"""#### 1.2.3 Multiple aggregate functions with `.agg()`
A wonderfully flexible method for performing multiple aggregating functions, .agg() can take a variety of input-formats to fit your needs.

To calculate multiple aggregates on one column, use a list of aggregate functions as strings.
"""

df.groupby('Department')['Salary'].agg(['mean', 'median'])

"""Aggregates can be applied to specific columns by using a dictionary of columns as keys and aggregate functions as values."""

df.groupby('Department').agg( {'Age':'max', 'Salary': 'mean'})

"""You can also give a list of functions as a value in your dictionary to perform more than one aggregate function on the same column."""

df.groupby('Department').agg( {'Age':'max', 'Salary': ['mean','max']})

"""Output columns can even be given custom names by providing named tuples as arguments."""

df.groupby('Department').agg( age_max=('Age', 'max'), salary_mean=('Salary', 'mean'))

"""### 1.3 Grouping on multiple features

`.groupby()` accepts several columns as a list, which creates groups with subgroups.

Let's find the average age and salary of each gender inside each department:
"""

df.groupby(['Department','Gender'])[['Age','Salary']].mean()

"""## Merging"""

new_data = {
    'Name': ['Alice', 'Bob', 'Claire', 'David', 'Emma', 'Alice', 'David', 'Erick'],
    'Age': [25, 30, 22, 28, 35, 25, 28, 21],
    'Department': ['IT', 'HR', 'Finance', 'IT', 'Marketing', 'HR', 'IT', 'Temp'],
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male'],
    'Salary': [50000, 60000, 45000, 70000, 80000, 52000, 72000, 31000],
    'Rating': [4.5, 3.8, 4.2, 4.0, 4.7, 4.3, 3.9, 4.1]
}
new_df = pd.DataFrame(new_data)

departments_data = {
    'Department': ['HR', 'Finance', 'Engineering', 'Marketing', 'IT'],
    'Location' : ['2nd floor', '2nd floor', '1st floor', '3rd floor', '1st floor'],
    'EstablishedYear': [2000, 1998, 2005, 2010,2002]
}
departments_df = pd.DataFrame(departments_data)
departments_df

new_df

"""### 2.1 .merge()

Often data from multiple sources needs to be considered together. Merging assures specified information is *aligned*, so that relevant pieces from the two DataFrames end up on the same row.

#### 2.1.1 Syntax

The `.merge()` method takes several agruments, so let's explore them:     
```
df.merge(df_2,
        left_on='df_column',      
        right_on='df_2_column',     
        how='inner')
```  
- `df` is the starting, or "left" DataFrame   
- The first argument, `df_2` is the DataFrame to merge with, also known as the "right"  
- `left_on` represents the column in the left DataFrame to join on  
- `right_on` represents the column in the right DataFrame to join on  
    - These columns should have shared information — values found in both DataFrames.
    - When each DataFrame has an appropriate column with the same name you can also use the single parameter `on` instead of `left_on` and `right_on`  
- `how` represents the type of merge (‘left’, ‘right’, ‘outer’, ‘inner’, ‘cross’). The default type is ‘inner’.

#### 2.1.2 Inner merge  
An inner merge will return only those rows for which matching information is present in *both* DataFrames.
"""

new_df.merge(departments_df, left_on='Department',right_on='Department',how='inner')

"""Notice that Erick does not appear in the merged DataFrame, because his position, Temp, is not listed in `departments_df`.

Likewise, there is nothing here about the Engineering department, because no employee is listed as working there.

#### 2.1.3 Left merge

A left merge will maintain *all* data from the left DataFrame, even if it does not align with a row of the right DataFrame.
"""

new_df.merge(departments_df, on='Department',how='left')

"""This time, Erick made it into the merged DataFrame, and his row shows null values in location and established year.

Again, nothing about Engineering, because nobody seems to work there.

#### 2.1.4 Right merge

A right merge will maintain *all* data from the right DataFrame, even if it does not align with a row of the left DataFrame.
"""

new_df.merge(departments_df, on='Department',how='right')

"""This time, a row in the merged DataFrame includes Engineering, but all columns with employee information contain null values.

Erick has been left out again, because there is no department for his Temp position.

## Challenges
"""

data1 = {
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco', 'London', 'Paris', 'Berlin', 'Rome', 'Tokyo'],
    'Country': ['USA', 'USA', 'USA', 'USA', 'USA', 'UK', 'France', 'Germany', 'Italy', 'Japan'],
    'Population (Millions)': [8.4, 3.9, 2.7, 2.3, 0.9, 8.9, 2.1, 3.7, 2.8, 13.9],
    'Area (km2)': [468.9, 502.8, 227.6, 1, 121.4, 1572, 105.4, 891.8, 1285, 2187],
    'Language': ['English', 'English', 'English', 'English', 'English', 'English', 'French', 'German', 'Italian', 'Japanese'],
    'Currency': ['USD', 'USD', 'USD', 'USD', 'USD', 'GBP', 'EUR', 'EUR', 'EUR', 'JPY'],
    'Continent': ['North America', 'North America', 'North America', 'North America', 'North America', 'Europe', 'Europe', 'Europe', 'Europe', 'Asia'],
    'Is_Capital': [False, False, False, False, False, True, True, True, True, True]
}

cities_info = pd.DataFrame(data1)
cities_info

data2 = {
    'City': ['New York', 'Chicago', 'Houston', 'London', 'Paris', 'Berlin', 'Rome', 'Tokyo', 'Lagos'],
    'Temperature (Celsius)': [18, 21, 30, 15, 19, 20, 24, 29, 34],
    'Humidity (%)': [65, 70, 75, 75, 80, 68, 72, 74, 83],
    'Rainfall (mm)': [50, 75, 20, 60, 40, 45, 35, 10, 122],
}

cities_weather = pd.DataFrame(data2)
cities_weather

"""### Challenge 1
Calculate the average population of cities in each continent using the groupby method
"""

# Your code here

cities_info.groupby('Continent')['Population (Millions)'].mean(numeric_only=True)

"""### Challenge 2
Find the city with the highest population in each country using the groupby method and agg function
"""

# Your code here

ci = cities_info.groupby('Country')['Population (Millions)'].max().reset_index()
ci
#cities_info.loc[ci,'City']
ci.merge(cities_info, on=['Country', 'Population (Millions)'], how='left')

"""### Challenge 3
Merge the cities_info and cities_weather DataFrames using a right join to keep only the cities for which weather data is available.
"""

# Your code here

cities_merged = cities_info.merge(cities_weather, on='City',how='right')
cities_merged

"""### Challenge 4
Group the cities by their 'Language' and find the total area and total rainfall for each language group
"""

# Your code here

cities_merged.groupby('Language')[['Area (km2)', 'Rainfall (mm)']].sum()

"""### Challenge 5
Calculate the sum of rainfall in each country using the groupby method.
"""

# Your code here

cities_merged.groupby('Country')['Rainfall (mm)'].sum()

"""### Challenge 6
Group the cities by their 'Continent' and find the average temperature and humidity for each continent
"""

# Your code here

cities_merged.groupby('Continent')[['Temperature (Celsius)', 'Humidity (%)']].mean()

"""### Challenge 7
Group the cities by their 'Is_Capital' and 'Language' columns and find the maximum population and minimum area for each combination.
"""

# Your code here

cities_merged.groupby(['Is_Capital','Language']).agg({'Population (Millions)': 'max', 'Area (km2)' : 'min'})
