# -*- coding: utf-8 -*-
"""08a_Pandas_plot.ipynb

Automatically generated by Colab.

# Data Visualization

Data visualization is an important part of working with data, as it allows you to explore your data, as well as communicate your findings to others. There are many python libraries that allow you to create beautiful plots. Today we will only look a the methods built in to Pandas. This functionality is super useful as it's very easy to use, so you can make very quick, basic plots, useful for exploring data.

## Import the Pandas library and create DataFrame

Before doing anything else, you'll need to import Pandas and get some data to work with.
"""

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Claire', 'David', 'Emma', 'Alice', 'David', 'Eva', 'Frank', 'Grace', 'Henry', 'Isabel', 'Jack', 'Katie', 'Liam', 'Mia', 'Nora', 'Oliver', 'Penny'],
    'Age': [25, 30, 22, 28, 29, 25, 28, 24, 33, 27, 29, 31, 23, 26, 32, 34, 30, 36, 28],
    'Department': ['IT', 'HR', 'Finance', 'IT', 'Marketing', 'HR', 'IT', 'Sales', 'Operations', 'Research', 'Engineering', 'Legal', 'Design', 'Customer Service', 'Product Management', 'Analytics', 'Quality Assurance', 'Human Resources', 'Customer Service'],
    'Gender': ['Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female'],
    'Salary': [50000, 60000, 45000, 70000, 80000, 52000, 72000, 48000, 65000, 55000, 75000, 90000, 51000, 62000, 73000, 85000, 68000, 78000, 54000],
    'Rating': [4.5, 3.8, 4.2, 4.0, 4.7, 4.3, 3.9, 4.1, 3.7, 4.4, 4.6, 3.5, 4.0, 4.2, 4.8, 4.3, 4.6, 4.1, 3.9],
    'Favourite_Colour': ['Blue', 'Red', 'Green', 'Yellow', 'Purple', 'Pink', 'Orange', 'Blue', 'Purple', 'Red', 'Purple', 'Yellow', 'Pink', 'Orange', 'Blue', 'Green', 'Red', 'Purple', 'Yellow']
}

df = pd.DataFrame(data)
df

"""## 1.&nbsp;  Plotting 1 variable

### 1.1.&nbsp;  `.hist()`

Histograms allow you to view the distribution of continuous numerical information. They are great for exploring data.
"""

df['Salary'].sort_values()

# histogram of the salary column
df['Salary'].hist();

"""From the histogram above we can see that salaries cluster into two groups: those with salaries roughly below 60,000€ and those with salaries around 70,000€ and above.

Pandas plotting is limited in terms of tweaking/customizing the plot, but you can still change some basic stuff. Here we'll adjust the number of bins in the histogram and the size of the figure.
"""

# bins are the amount of coulmns the histogram is divided into. The more bins, the finer the detail that can be seen
# try changing the number of bins and running this cell again, how has the histogram changed?

# why not try also changing the figsize numbers one at a time and running the cell again, what changed?

df['Salary'].hist(bins=12, figsize=(12,6));

"""### 1.2.&nbsp; `.plot.bar()`

Bar plots are for visualising categorical data, such as the number of people working in each department. This would require two steps:
1. Group the categories and generate the frequencies with `value_counts()`
2. Use `.plot.bar()` to create a graph

For simple frequency plots, which show us how many values are in each category:

1. You should first group the categories and generate the frequencies with `value_counts()`

2. You should use a **bar plot** rather than a histogram, as we're now using categorical data instead of numerical
  - Numerical data - histogram
  - Categorical data - bar plot

Let's see this in action:
"""

# 1. group the categories and generate the frequencies with value_counts()
colour_freq = df['Favourite_Colour'].value_counts()
colour_freq

# 2. plot our value_counts from above as a bar plot
colour_freq.plot.bar();

"""Similar to `.hist()`, there are some parameters available in `.plot()` that you can use to improve your plots, such as color or size. The documentation is always the ultimate source of truth when it comes to understanding which parameters you can tweak and how to do it:

- [These are the docs specifically for `DataFrame.plot.bar()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.bar.html)
- [Here are the docs for `DataFrame.plot()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.html#pandas.DataFrame.plot), with arguments that apply to all types of plots, not just bar plots.
"""

# changing the colors of the bars
colour_freq.plot.bar(color=["purple", "blue", "red", "yellow", "green", "pink", "orange"]);

"""###### **Exercise 1:**
Make a bar plot for the departments people work in. Highlight information technology (IT) in a brighter color.
> Tip: if you want to use prettier colors, you'll find some [here](https://matplotlib.org/stable/gallery/color/named_colors.html)


"""

# your code here
ba = df['Department'].value_counts()
colors = ['purple' if dept == 'IT' else 'lightgray' for dept in ba.index]

ba.plot.bar(color=colors)

"""## 2.&nbsp; Plotting 2 or more variables

### 2.1.&nbsp; `.plot.scatter()`

Whenever you want to see if there is a relationship between two numerical variables, you could compute something complicated like a linear correlation coefficient, or perform more sophisticated statistical tests. For a nice intuitive grasp of the numbers, however, nothing beats a good old scatter plot.
"""

df.plot.scatter(x='Age', y='Salary');

"""Scatter plots allow us to quickly see a strong/weak correlation at a glance. You can see a slight trend in the above scatter plot, showing that, on the whole, older people tend to have higher salaries than younger ones.

Let's tweak some of the scatter plots parameters:

- The `c` argument allows **colors** to depend on the values of another (numerical) column.
- The `cmap` argument allows the usage of "**color maps**" to fill the dots. See all available cmaps [here](https://matplotlib.org/stable/tutorials/colors/colormaps.html)
- The `s` argument modifies the **size of the dots**.
- The `figsize` argument defines the **size of the whole plot**.

> **Note:** Some of these options might only be available if you have one of the latest Pandas versions, as `pandas.plot()` is one of the areas where pandas is growing. You can check your pandas version with `pd.__version__` in the notebook. If your version is substantially older than the one shown in [here](https://pandas.pydata.org/docs/index.html), consider updating pandas by typing on your Terminal `pip install --upgrade pandas`.
"""

# This is the same scatter plot as above, just bigger, more colorful, and now with an added third variable 'Rating'.
df.plot.scatter(x='Age',
                y='Salary',
                c='Rating',
                s=350,
                cmap="viridis",
                figsize=(12,8)
                );

"""## 3.&nbsp; Challenges:
Use the `vehicles.csv` dataset to create the plots in the following exercises.
"""

url = 'https://drive.google.com/file/d/18zYGrzRhn_mz1HJLXxSO_MwR0_nWBS3K/view?usp=sharing' # vehicles.csv
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
cars = pd.read_csv(path)

#Add a column that states if a car's transmission is automatic or manual:
cars["Auto"] = cars["Transmission"].str.contains("Auto")
cars

"""###### **Exercise 2:**
how many cars have Automatic or Manual transmission?

As we are only plotting 1 variable, please feel free to check out the section above `Plotting 1 variable`


"""

# your code here

cars.Auto.replace([True,False],['Auto', 'Manual']).value_counts().plot.bar();

"""###### **Exercise 3:**
how many cars have each type of Drivetrain? Highlight "All-Wheel Drive" in a different color to everything else
"""

# your code here

# your code here

drivetrain = cars.Drivetrain.value_counts()
drivetrain.plot.bar(color = ['palegoldenrod', 'palegoldenrod', 'goldenrod','palegoldenrod',
                             'palegoldenrod', 'palegoldenrod', 'palegoldenrod', 'palegoldenrod']);

"""###### **Exercise 4:**
represent the relationship between fuel consumption (`Combined MPG`) and the number of `Cylinders` a car has, using a scatterplot:

  > **Tip**: we went through scatter plots in the section above `Plotting 2 or more variables`

"""

cars.plot.scatter(x='Combined MPG', y='Cylinders');

"""###### **Exercise 5:**
explore the same relationship as in exercise 4, but this time use a [boxplot](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.boxplot.html):
"""

cars.boxplot('Combined MPG','Cylinders')

"""###### **Exercise 6:**
create a plot that displays the evolution of the average CO2 emissions by cars over the years.
  > **Tip**: first you'll need to find the average CO2 per year, and then plot this


"""

# your code here

year_groups = cars.groupby('Year')["CO2 Emission Grams/Mile"].mean()

year_groups.plot()
