# -*- coding: utf-8 -*-
"""09a_functions.ipynb

Automatically generated by Colab.


# Functions

There are times when you may wish to perform the same operation over and over. It could be an analysis repeated every day, or a common calculation, or some custom sort of data cleaning you use often.

Functions allow you to take the steps of an operation, give them a name, and call them as often as you like. We've actually used many functions already — things like `len()` and `float()` are "built-in" functions in Python, and methods are functions "attached" to specific data types.

Today, you'll learn to write your own, custom functions. Any lines of code that get used more than once are good candidates to be made into a function.

We'll follow 3 easy steps:
1. Write some lines of code that do the job you wish done — basically normal coding
2. Indent the lines of code — this will all become part of the function
3. Add `def` and `return` statements — this is what makes the code a function

## 1.&nbsp; A function with one argument

Though it may seem simple, making a function to perform division will show the necessary steps.

### 1.1 Write some code

Let's start out by dividing a number by 2:
"""

a = 3

div = a/2
div

"""Notice that above there is a separation between assiging the value and performing the operation. That's because the function should be able to accept any value, not just the ones assigned for a specific case.

If you go and change the value of `a` , the cell containing `div` will still run just fine. That's a good sign.

### 1.2 Indent the code

We won't run this cell, just show how you'll want to take the operational code and indent it. The indent will show "This code belongs to the function," just as in loops and conditional statements.
"""

div = a/2
    div

"""We've also left a blank line at the top. That's to leave space for step 3.

### 1.3 Add `def` and `return` statements
"""

def division (a):
    div = a/2
    return div

"""Let's break down what's happened line by line:
- Line 1:      
&emsp; `def` is the keyword that means "I am defining a function now"     
&emsp; `division` is the name of the function; this will be used later to call it into action     
&emsp; `(a)` is the function's input; this is how a function accepts different values, making it a versatile tool      
&emsp; `:` signals "the function starts on the next line", just like with loops and `if` statements
- Line 2:     
&emsp; nothing has changed here, but notice that we named `(a)` above to match the variable used inside the function
- Line 3:    
&emsp; `return` is used to declare the function's output; this is the value we're interested in when performing the operation

### 1.4 Call the function

Our function now has a name `division` which we can use along with an *argument* to call it.
"""

division(4)

"""When calling `division` with an argument of `4`, the variable `a` inside the function takes the value `4`, which is then divided by `2`, resulting in the output `2.0`.

The argument of a function can be another variable:
"""

argument = 3.1415
division(argument)

"""We saw the result of our function above on the screen, but it is also possible to save a function's output as a variable:"""

b = division(56)

print(f"The value of b is {b}")

"""### **A note on variables in functions:**
Even though we've given `division` many different arguments by now, this has not altered the value of `a` set at the top of the notebook, even though they have the same name.
"""

a

"""Variables internal to a function exist *only to that function*.

## 2.&nbsp; A function with many arguments

A function can take more than one argument.

### 2.1 Write some code
"""

# Start with many variables
n1 = 54
n2 = 78
n3 = 43
n4 = 66
n5 = 51

# This code is written to look complicated, but is ultimately meaningless
mean = (n1+n2+n3+n4+n5)/5
if ((n1*mean + n2/mean)/n3) > n4/n5:
    complex_output = n4/n5
else:
    complex_output = 0
complex_output

"""### 2.2 Indent the code"""

mean = (n1+n2+n3+n4+n5)/5
    if ((n1*mean + n2/mean)/n3) > n4/n5:
        complex_output = n4/n5
    else:
        complex_output = 0
    complex_output

"""### 2.3 Add `def` and `return` statements"""

def complex_operation(n1, n2, n3, n4, n5):
    mean = (n1+n2+n3+n4+n5)/5
    if ((n1*mean + n2/mean)/n3) > n4/n5:
        complex_output = n4/n5
    else:
        complex_output = 0
    return complex_output

"""### 2.4 Call the function"""

complex_operation(8, -9, 12, 4, -1)

"""## 3.&nbsp; Positional and Keyword arguments

There are different ways to assign which argument is assigned to which variable inside a function.

We'll start by writing a function that prints the values of its arguments.
"""

def some_function (x, y, z):
    print(f"""x has the value {x}
y has the value {y}
z has the value {z}""")

"""### 3.1 Positional arguments
By default, arguments will be assigned *in order* to the variables named in the function definition. These are known as "positional arguments".
"""

some_function(6, 8, 'some word')

"""### 3.2 Keyword arguments

Arguments can be identified by name instead of position. They follow the pattern     
`variable_name=value`     
and are known as "keyword arguments" and can be entered in any order.
"""

some_function(y=6, z=8, x='some word')

"""### 3.3 Mixing positional and keyword arguments

When mixing positional and keyword arguments, *unnamed arguments* will be assigned *positionally*.

Here, since `6` is not assigned by name, its position will cause it to be assinged to `x`.
"""

some_function(6, z=8, y='some word')

"""Positional arguments cannot follow keyword arguments.

Since `6` has no given name below, it is considered a positional agrument.
"""

some_function(z=8, y='some word', 6)

"""## 4.&nbsp; Default values

Default values can be set for functions. If an argument has a default, that value will be used if no other is assigned during the function call.

A default is assigned on the function's definition line.
"""

# b is given the default value of 2
def default_division (a, b=2):
    div = a/b
    return div

"""The function will divide any two numbers."""

default_division(3, 4)

"""Providing only one argument will cause the default `2` to be used for `b`."""

default_division(3)

"""## 5.&nbsp; Exercises:

### Exercise 1:

Build a function to filp coins. It should take as an argument how many coins to flip, and output how many times the coin landed on heads.

Hint: use the module `random` inside of your function!
"""

# Embrace the process and flex your problem-solving

import random

def cointoss(n):
  heads_count = 0
  for i in range(n):
    coin_side = random.choice(['heads', 'tails'])
    if coin_side == 'heads':
      heads_count+= 1
  return heads_count

# Don't get turned around, just try some things out

cointoss(3000)

"""### Exercise 2:

Build a function that takes as input a string and returns it reversed

Extra challenge: try not to use any built in Python string method!

Test your function:
"""

# One step at time builds the shining path

def string_reverse(given_word):
    word_to_reverse = ''
    letter_count = len(given_word)
    while letter_count > 0:
      word_to_reverse += given_word[letter_count-1]
      letter_count = letter_count-1
    return word_to_reverse

string_reverse("Abracadabra")

# expected output: 'arbadacarbA'

"""### Exercise 3:

Build a function to return the intersection of two sets

Find out more about Python sets here: https://www.w3schools.com/python/python_sets.asp
"""

def intersect(set1, set2):
  result = set()
  for i in set1:
    if i in set2:
      result.add(i)
  return result

# test your function
small_primes = (1, 2, 3, 5, 7, 11, 13)
fibonacci = [0, 1, 1, 2, 3, 5, 8, 13]

intersect(small_primes, fibonacci)

# expected output: {1, 2, 3, 5, 13}

# Should work with strings as well
plane = "plane"
planet = "planet"

intersect(plane, planet)
# expected output: {"a", "e", "l", "n", "p"}

"""## 6.&nbsp; **BONUS:** Modules

You can save a notebook as Python script (a file with the `.py` extension). Then, it automatically becomes a Python "module". These modules can be imported the same way you import `pandas`, and then you can access any functions within them.

This allows you to keep your functions in a clean and isolated place, where they will be less prone to getting "corrupted". Your notebook will also be cleaner without all the function definitions.

Using modules is easier when working locally (with Jupyter Lab, for example).
- Working locally, put your `.py` file and your notebook in the same folder.
- With Google Colab, there's an extra step involved. Follow the instructions in [this video](https://www.youtube.com/watch?v=YP6APKLRf58).

Once that is done, use `import` to gain access to the module. For example, if the function `my_function` were in the file "my_module.py", it would be used like this:
```
import my_module
...
my_module.my_function(arg1, arg2...)
```

**Exercise:** Convert the function from the previous exercise into a module and import it to this notebook.
"""

# Follow the steps and try it out

"""## 7.&nbsp; **BONUS:** More about arguments and `return`

### 7.1 No arguments
A function does not have to have arguments. However, `( )` still needs to make an appearance in the definition and the call.
"""

def hello_world():
    return "hello world"

hello_world()

"""### 7.2 No return
A function does not have to have a `return` statement.
"""

def hello_world2():
    print("hello world")

hello_world2()

"""We still see "hello world", but the function has made an *implicit return* of `None`. Trying to save the output to a variable reveals the behaviour."""

this = hello_world2()

print(f"The output is {this}, and has type {type(this)}.")

"""When choosing to use `return` or `print()`, ask yourself if you need to use the result of your operation anywhere else in the code. If so, use `return`.

If informing the user is the *only* goal, `print()` can do the job. Keep in mind though, that if your function exists as part of a larger process, introducing a `NoneType` to that process could cause disruptions.

There's no hard rules, just consequences.

### 7.3 Multiple returns
A function can return multiple values if they are separated by commas.
"""

def multiple_return():
    i = "some text"
    j = "more text"
    k = "final text"
    return i, j, k

first, second, third = multiple_return()
print(first)
print(second +" and "+ third)
