# -*- coding: utf-8 -*-
"""1_webScraping__structure.ipynb

Automatically generated by Colab.

# Web scraping

Web scraping is a technique used to extract data from websites. It involves sending HTTP requests to websites, parsing the returned HTML code, and extracting the desired data. Web scraping is a powerful tool for data scientists as it allows them to collect large amounts of data from the web. This data can then be used to train machine learning models, analyse trends, and make informed business decisions.

---
## 1.&nbsp; Import libraries 💾
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup

"""---
## 2.&nbsp; Beautiful Soup 🍲

[Beautiful Soup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) is a Python library that simplifies the process of web scraping. It provides a user-friendly interface for parsing HTML documents, enabling users to extract specific information from websites. Through Beautiful Soup, you can navigate the HTML tree structure, locate elements based on their tags, attributes, and content, and extract the desired data into a structured format.

To illustrate how to use Beautiful Soup, we'll use the simplified mock website below. This stripped-down version serves as a practical learning tool, as real websites often possess much larger and more complex HTML structures. By starting with this simplified model, you can gradually build your skills and expertise, ensuring a solid understanding of the core concepts before tackling more intricate web scraping tasks.
"""

html_doc = """
<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie" class="sister" id="link1" meta="Eldest sister">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2" meta="Middle sister">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3" meta="Youngest sister">Tillie</a>;
and they lived at the bottom of a well.</p>

<p class="story">...</p>
"""

"""
Beautiful Soup's HTML parser takes the raw, unruly HTML code and transforms it into a neatly organised tree structure, making the information easily accessible and manageable."""

soup = BeautifulSoup(html_doc, 'html.parser')

"""We can see the tree structure using Beautiful Soup's `.prettify` attribute."""

print(soup.prettify())

"""---
## 3.&nbsp; Navigating html for beginners 🧭
There are many methods in Beautiful Soup to explore the html data. By far the most popular and useful of these is `.find_all().` So, naturally, this is where we'll start our journey.

### 3.1.&nbsp; `.find_all()`
The `.find_all()` method in Beautiful Soup returns a list of all the elements that match the specified criteria, such as tag name, class name, or attribute values.

#### 3.1.1.&nbsp; Searching by tag

The tags are the letter/word at the beginning of the angle brackets. For example, below, these brackets have an `a` tag.

`<a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">Elsie</a>`

The `.find_all()` method takes a string argument and returns a list of all matching HTML tags within the current document. If no matching tags exist, an empty list is returned.
"""

soup

soup.find_all("title")

soup.find_all("p")

"""#### 3.1.2.&nbsp; Searching by attribute

Attributes are the other information in the angle brackets. For example, below, these brackets have a `class`, `href`, `id`, and `meta` attribute.

`<a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">Elsie</a>`

Attributes provide additional context and functionality to the elements. They can serve various purposes, including CSS selectors for styling, URLs for linking to external resources, metadata for storing relevant data, and a multitude of other information-bearing components. By leveraging these attributes, we can effectively target specific sections of the website.

##### 3.1.2.1.&nbsp; CSS selectors
CSS selectors are used to to style certain sections of websites. This makes them very helpful for webscraping as we can then target certain regions of the website.

###### 3.1.2.1.1.&nbsp; Class
Class selectors are used to style **multiple** HTML elements that share a common characteristic or function.
> **Note:** here class has an underscore at the end of the word, this is because class is a reserved keyword in python.
"""

soup.find_all(class_="sister")

"""###### 3.1.2.1.2.&nbsp; ID
ID selectors are used to style **single** HTML elements.
"""

soup.find_all(id="link1")

soup.find_all(id="link2")

"""##### 3.1.2.2.&nbsp; Other attributes
HTML elements can also include other attributes, which can be equally useful for identifying and targeting specific data points. To locate these attributes, search for them using the same method as you do for CSS selectors.
"""

soup.find_all(meta="Youngest sister")

"""#### 3.1.3.&nbsp; Searching by string
The text (string) is the part between the opening and closing angle brackets, this is what's displayed on the webpage. For example, below, these brackets have `Elsie` as the text.

`<a class="sister" href="http://example.com/elsie" id="link1" meta="Eldest sister">Elsie</a>`

Instead of searching for specific tags or attributes, you can also search for this text. To do this, you can use a string or a regular expression to specify the text you're looking for.
"""

soup.find_all(string="Dormouse")

"""The string "Dormouse" didn't return any results because BeautifulSoup searches for entire strings that exactly match the string you entered. In other words, the string must be the exact same as what you're searching for for it to be considered a match."""

soup.find_all(string="The Dormouse's story")

"""To search for a substring, the easiest way is to use the regular expressions method `.compile()`."""

import re
soup.find_all(string=re.compile("sister", re.IGNORECASE))

"""> **Note:** by default, the .compile() method is case-sensitive, meaning it will only match strings that are exactly equal to the pattern you specify, including case. To perform case-insensitive matching, you must explicitly pass the re.IGNORECASE flag to the .compile() method.

### 3.2.&nbsp; Extracting text
There are a few ways to extract text in Beautiful Soup, here we'll focus on 2 of them.

#### 3.2.1.&nbsp; `.get_text()`
The `.get_text()` method extracts all the human-readable text from a Beautiful Soup object, returning it as a string.
"""

soup.find_all("title")

soup.find("title").get_text()

soup.find_all("title")[0].get_text()

"""> Read the error message and look at the output from the cell above. Can you work out why we got an error?"""

# @title Click `show code` to see the solution to the error

# It was a list, read the error messages and notice the square brackets in the original output
# Therefore, we need to select the first and only element of this list
soup.find_all("title")[0].get_text()

"""We can also print out multiple items using our looping skills."""

story = soup.find_all("p")
story

for p in story:
  print(p.get_text())

"""#### 3.2.2.&nbsp; Extracting attributes:
HTML elements often store additional information within their attributes. To extract this data using Beautiful Soup, you can append square brackets after the element selector and specify the attribute name within them.
"""

soup.find_all(id="link1")

soup.find_all(id="link1")[0]['href']

soup.find_all(id="link1")[0]['meta']

"""## Challenge 1 😀
Below is new HTML code. Use your scrapping skills to answer the questions.
"""

geography = """
<!DOCTYPE html>
<html>
<head> Geography</head>
<body>

<div class="city">
  <h2>London</h2>
  <p>London is the most popular tourist destination in the world.</p>
</div>

<div class="city">
  <h2>Paris</h2>
  <p>Paris was originally a Roman City called Lutetia.</p>
</div>

<div class="country">
  <h2>Spain</h2>
  <p>Spain produces 43,8% of all the world's Olive Oil.</p>
</div>

</body>
</html>
"""

# Create the "soup"

soup = BeautifulSoup(geography, "html.parser")

# 1. All the "fun facts"

fun_facts = soup.find_all("p")
for p in fun_facts:
  print(p.get_text())

# 2. The names of all the places.

places = soup.find_all("h2")

for p in places:
  print(p.get_text())

# 3. All the content (name and fact) of all the cities (only cities, not countries!)

cities = soup.find_all("div", class_="city")

for city in cities:
    name = city.find("h2").get_text()
    fact = city.find("p").get_text()
    print(name, "-", fact)

# 4. The names (not facts!) of all the cities (not countries!)

cities = soup.find_all("div", class_="city")

for city in cities:
    print(city.find("h2").get_text())

"""---
## 4.&nbsp; Navigating html with a few more advanced techniques 🗺️

### 4.1.&nbsp; `.find()`
`.find()` is similar to `.find_all()`, but it returns only the first element that matches the specified criteria. This makes it useful when you know exactly where the element you're looking for is located and you only need to retrieve one instance of it.
"""

soup.find('p')

"""### 4.2.&nbsp; `.select()`
`.select()` is similar to `.find_all()`, but there are 2 main differences:
- the way we write our query in the brackets is slightly different
- `.select()` allows you to chain CSS selectors together to navigate through the HTML structure, enabling you to select elements based on their positions within nested elements or patterns. This makes it particularly useful for extracting data from complex HTML structures.

In contrast, `.find_all()` uses a simpler syntax based on tag names and attributes, making it more straightforward for basic element selection.

Here's how we query with `.find_all()`
"""

soup.find_all('a', class_='sister')

"""Here's the same query with `.select()`"""

soup.select('a.sister')

"""To demonstrate the power of `.select()` in navigating through nested elements, let's extract all the `<a>` tags with the id `'link2'` that are within `<p>` tags with the class `'story'`."""

soup.select('p.story a#link2')

"""### 4.3.&nbsp; Navigating to the Next or Previous Element
In some cases, you may need to access specific elements that are closely related to others, but their HTML structure doesn't provide unique identifiers. To overcome this challenge, you can utilise the `.find_next()` and `.find_previous()` methods to navigate through the HTML structure and reach the desired element.
"""

last_link = soup.find(id='link3')
last_link

"""#### 4.1.1.&nbsp; `.find_next()`
`.find_next()` moves forward one element
"""

#last_link.find_next()

"""#### 4.2.&nbsp; `.find_previous()`
`.find_previous()` moves back one element
"""

#second_to_last = last_link.find_previous()

#second_to_last.find_previous()

"""---
## 5.&nbsp; Showcasing these skills on a real website 💻
Let's see what information we can get from the wikipedia site for web scraping

### Loading the html
"""

url = "https://en.wikipedia.org/wiki/Web_scraping"
headers = {'User-Agent': 'Chrome/134.0.0.0'}

response = requests.get(url, headers=headers)

soup_3 = BeautifulSoup(response.content, 'html.parser')

"""> While we haven't yet looked into the requests library, we'll postpone delving into it today to avoid overwhelming you with too much new information. Instead, we'll explore the requests library when we start gathering weather data later in the project."""

print(soup_3.prettify())

"""### Getting the title"""

soup_3.find("title").get_text()

"""### Getting the first h1 tag"""

soup_3.find("h1").get_text()

"""### Getting all the h2 tags"""

h2_tags = soup_3.find_all("h2")
h2_tags

"""As we have multiple tags in the list here, we need to use a loop to print them out."""

for h2 in h2_tags:
  print(h2.get_text())

"""### Selecting the `Legal Issues` text for only `India`
> **Pro tip:** If you're using Google Chrome, you can navigate to `View > Developer > Inspect elements` to access the built-in web development tools. Here, you can explore the HTML structure of the webpage directly within the browser using your mouse. This interactive approach is often more intuitive than examining the raw HTML code.

By investigating the html we can see that the closest, easy to access, tag is the heading with the CSS `id` of `"India"`.
"""

soup_3.find(id="India")

"""We can then use `.find_next()` to select the text."""

soup_3.find(id="India").find_next()

"""Looks like the next tag was a `span` tag, so let's specify that we want the next `p` tag."""

soup_3.find(id="India").find_next("p")

"""Now we can simply extract the text, and we have what we need"""

soup_3.find(id="India").find_next("p").get_text()

"""## Challenge 2 😀

Utilise your web scraping skills to gather information about three German cities – Berlin, Hamburg, and Munich – from Wikipedia. You will start by extracting basic information: the country, the latitude and the longitude of each city and then expand to more dynamic data such as the population.

1. Scraping Basic Information

  1.1. Begin by scraping the country, the latitude and the longitude of each city from their respective Wikipedia pages:

 - Berlin: https://en.wikipedia.org/wiki/Berlin
 - Hamburg: https://en.wikipedia.org/wiki/Hamburg
 - Munich: https://en.wikipedia.org/wiki/Munich

  1.2. Once you have scraped the basic information of each city, reflect on the similarities and patterns in accessing them across the three pages. Also, analyse the URLs to identify any commonalities. Make a loop that executes once and retrieves the country, latitude, and longitude for all three cities.

2. Data Organisation

  2.1 Utilise pandas DataFrame to effectively store the extracted information. This DataFrame should have a row for each city, and columns for each type of information (cityname, country, latitude, longitude). If you feel brave, change latitude and longitude into decimal format.

  2.2 Looking ahead (optional): Create a function from the loop and DataFrame to encapsulate the scraping process. This function can be used repeatedly to fetch updated data whenever necessary. It should return a clean, properly formatted DataFrame.

## BONUS Challenge 3: Population

  3.1. Expand the scope of your data gathering by extracting the population of a city. This information changes over time, so we might need to add a timestamp.

  3.2. Organise your information in a DataFrame and wrap it in a separate function.

## BONUS Challenge 4: Global Data Scraping

  With your robust scraping skills now honed, venture beyond the confines of Germany and explore other cities around the world. While the extraction methodology for German cities may follow a consistent pattern, this may not be the case for cities from different countries. Can you make a function that returns a clean DataFrame of information for cities worldwide?
"""

headers = {'User-Agent':'WBS browser 1.0'}
response = requests.get('https://en.wikipedia.org/wiki/Berlin',headers=headers)

city_soup = BeautifulSoup(response.content, 'html.parser')

#coordinates
lat = city_soup.find(class_='latitude').text
lon = city_soup.find(class_='longitude').text

#country
city_soup.find_all(class_='infobox-data')[0]

country = city_soup.find('th', string='Country').find_next('td').text

print(f'Country : {country}, lat-lon: {lat}{lon}')

def get_city_data(city):
  headers = {'User-Agent':'WBS browser 1.0'}
  response = requests.get('https://en.wikipedia.org/wiki/Berlin',headers=headers)
  city_soup = BeautifulSoup(response.content, 'html.parser')
  #coordinates
  lat = city_soup.find(class_='latitude').text
  lon = city_soup.find(class_='longitude').text
  #country
  city_soup.find_all(class_='infobox-data')[0]
  country = city_soup.find('th', string='Country').find_next('td').text
  print(f'Country : {country}, lat-lon: {lat}{lon}')

cities = ['Hamburg', 'Munich', 'Berlin', 'Granada', 'Santiago', 'Toronto', 'Paris']
for city in cities:
  print('city:', city)
  get_city_data(city)

