# -*- coding: utf-8 -*-
"""2-lists-dictionaries.ipynb

Automatically generated by Colab.

# &nbsp;1. Lists

As we are to become Data Scientists, we will need objects that can store multiple elements. Those kind of objects are called **collections**.

In Python, the **list** is one of the most useful collections.

## 1.1 Create

You can create a list with `[]`, and separate the elements with a comma.
"""

# https://www.w3schools.com/python/python_lists.asp

weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

"""A list can also contain numbers."""

leap_years = [2000, 2004, 2008, 2012, 2016, 2020]

"""You can create a list out of something else with `list()`."""

# https://www.w3schools.com/python/ref_func_list.asp

list("WBSCS")

"""**Empty list**

Sometimes, we need to create a list without knowing what we will store in it later on.
"""

empty_list = []

"""## 1.2. Access

In Python, we call the location of an element in a list its **index**.

Python lists are zero-indexed. This means that the first element in a list has index 0, rather than 1.
Here are the index numbers for the list `weekdays`:

| Element   | index |
|-----------|---|
| Monday    |   0   |
| Tuesday   |   1   |
| Wednesday |   2   |
| Thursday  |   3   |
| Friday    |   4   |
| Saturday  |   5   |
| Sunday    |   6   ||

We can select a single element from a list by using square brackets `[ ]` and the index of the list's item. If we wanted to select the third element from the list, we would therefore use `weekdays[2]`.
"""

weekdays[2]

"""What if we wanted to select the last element of a list?

We can use the index -1 to select the last item of a list, even when we don’t know how many elements are in that list. Here are the negative index numbers for our `weekdays` list.

| Element   | index |
|-----------|---|
| Monday    |  -7   |
| Tuesday   |  -6   |
| Wednesday |  -5   |
| Thursday  |  -4   |
| Friday    |  -3   |
| Saturday  |  -2   |
| Sunday    |  -1   ||
"""

weekdays[-1]

weekdays[0:3]

"""## 1.3. Data types

Lists can contain any data type in Python! For example, this list contains a string, an integer, a boolean, and a float.
"""

mixed_list = ["Mia", 27, False, 0.5]

"""## 1.4. Update

We can change a single element by specifying its index and overwriting its value.
"""

garden = ["Tomatoes", "Green Beans", "Cauliflower", "Grapes"]

garden[2] = "Strawberries"

print(garden)

"""One of the most useful functions we will use in combination with lists is `append()`: it just adds an element at the end of the list."""

# https://www.w3schools.com/python/ref_list_append.asp

leap_years.append(2024)
print(leap_years)

"""When we want to add multiple items to a list, we can use `+` to combine two lists.

This is also known as concatenation.
"""

leap_years = leap_years + [2028, 2032]
print(leap_years)

"""The `insert()` function does the same, but at any specified position:"""

# https://www.w3schools.com/python/ref_list_insert.asp

leap_years.insert(0, 1996)
print(leap_years)

leap_years.insert(2, "Happy new millenium")
print(leap_years)

"""## 1.5. Remove

We can remove elements in a list using the `.remove()` method.
"""

leap_years.remove("Happy new millenium")
print(leap_years)

"""There are some other built-in methods that you can use to manipulate lists. Check them out [here](https://www.w3schools.com/python/python_lists_methods.asp) and complete the following exercises.

## 1.6. Two-dimensional lists

We already saw that the items in a list can be both numbers or strings. But lists can contain other lists, too! We will commonly refer to these as two-dimensional (2D) lists.
"""

heights = [["Noelle", 61], ["Ava", 70], ["Sam", 67], ["Mia", 64]]
print(heights)

"""Two-dimensional lists can be accessed similarly to one-dimensional lists. Instead of providing a single pair of brackets `[ ]`, we will use an additional set for the second dimension.  
Here are the index numbers to access data for the list `heights`:

| **Element** | Index |
|-------------|-------|
| Noelle      | [0][0] |
| 61          | [0][1] |
| Ava         | [1][0] |
| 70          | [1][1] |
| Sam         | [2][0] |
| 67          | [2][1] |
| Mia         | [3][0] |
| 64          | [3][1] |
"""

heights[0][1]

"""## 1.7. Exercises"""

# Some lists to work with
car_brands = ["BMW", "Volkswagen", "Mercedes", "Ford", "Apple", "Toyota",
              "Tesla", "Kia", "Porsche", "Mazda", "Honda", "Jaguar",
              "Mitsubishi", "Audi", "Bentley", "Bugatti", "Chrysler"]

fibonacci = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 53, 89, 144]

characters = [["Harry", "Hermione", "Ron"],
              ["Daenerys Targaryen", "Jon Snow", "Tyrion Lannister",
               "Cercei Lannister", "Arya Stark", "Sansa Stark"],
              ["Aragorn", "Gandalf", "Frodo", "Legolas", "Gollum", "Gimli"],
              ["Walter White", "Jesse Pinkman", "Gus Fring"]
             ]

sex_and_the_city = ["Carrie", "Samantha", "Charlotte", "Miranda"]

numbers = [[1, 51, 59, 2, 95, 25, 28, 67, 14, 63, 84, 33, 56, 31, 54, 97, 77,
            98, 46, 84, 6, 66, 86, 77, 69, 19, 77, 7, 76, 19, 59, 77, 28, 34,
            94, 4, 45, 95, 41, 66, 5, 38, 35, 57, 84, 38, 94, 65, 45, 80, 83,
            22, 12, 100, 52, 55, 31, 69, 29, 67, 4, 39, 87, 49, 81, 82, 96, 4,
            85, 62, 90, 72, 70, 26, 29, 63, 48, 94, 58, 9, 49, 79, 33, 63, 41,
            13, 90, 37, 31, 3, 11, 54, 56, 72, 91, 97, 2, 83, 82, 6]]

"""#### Exercise 1

Find the position of "Bugatti" in the `car_brands` list (whether it is the 3rd element, the 5th...).
"""

# What could be?
car_brands.index("Bugatti")

"""##### Hint"""

# _____.index(_____)

"""#### Exercise 2

Remove "Apple" from the `car_brands` list.
"""

# Don't be afraid to be wrong!

car_brands.remove("Apple")
car_brands

"""##### Hint"""

# _____.remove(_____)

"""#### Exercise 3

Order the `car_brands` list alphabetically.
"""

# Your code is a masterpiece in the making

car_brands.sort()
car_brands

"""##### Hint"""

# _____.sort(_____)

"""#### Exercise 4

There's a mistake in the list with the fibonacci sequence, fix it.
"""

# Let's code!

fibonacci[10] = 55
fibonacci

"""##### Hint"""

# fibonacci___ = 55

"""#### Exercise 5

Order the `fibonacci` list descending.
"""

# With every line of code, you're making progress.

fibonacci.reverse()
fibonacci

"""##### Hint"""

# _____.sort(_____=True)

"""#### Exercise 6

Add "Hagrid" and "Dumbledore" to the first list inside the `characters` list.
"""

# With every error, you're one step closer to finding the solution.

characters[0].append("Hagrid")
characters[0].append("Dumbledore")
characters

"""##### Hint"""

# _____[0].append(_____)
# characters[0]._____('Dumbledore')

"""#### Exercise 7

Add the `sex_and_the_city` list to the `characters` list.
"""

# You've got this! Break down the problem and conquer it step by step.

characters.append(sex_and_the_city)

"""##### Hint"""

# _____.append(sex_and_the_city)

"""#### Exercise 8

Remove all elements from the `sex_and_the_city` list.
"""

# Be bold!
sex_and_the_city.clear()

"""##### Hint"""

# sex_and_the_city._____()

"""#### Exercise 9

Sum all elements in the `numbers` list and save the sum to the variable `total`.
"""

# We're all learning here!

total = sum(numbers[0])
total

"""##### Hint"""

# total = _____(_____[0])

"""#### Exercise 10

Find out how often the number `77` appears in the `numbers` list.
"""

# Make your code shine!

numbers[0].count(77)

"""##### Hint"""

# numbers[0]._____(77)

"""# &nbsp;2. Dictionaries

So far, we learned how to use lists. Now, we will learn about **dictionaries**.

The dictionary is an **ordered** (as from Python version 3.7) and **changeable** collection that contains

* key-value pairs

* separated by commas

* inside curly brackets.

## 2.1. Create

An example of a dictionary.
"""

dictionary = {'Germany':'Berlin', 'France':'Paris'}
dictionary

"""Germany and France are the **keys** and Berlin and Paris are the coresponding **values**.

Empty dictionary:
"""

empt_dict = {}
empt_dict

"""Dictionaries can't have duplicated key-value pairs."""

dupl_val_dict= {1:1,2:2,1:1}
dupl_val_dict

"""## 2.2. Access

If we want to access a **value** inside a dictionary, we can do so with the **key** in square brackets.
"""

dictionary['Germany']

dictionary['France']

"""We can also acces values with the **get()** method."""

dictionary.get('Germany')

"""To retrieve a list of all the keys inside a dictionary, we use the **keys()** method."""

big_dict = {'English': 85, 'Math': 72, 'Science': 79, 'Art': 88}

big_dict.keys()

"""To retrieve a list of all the values inside a dictionary, we use the **values()** method."""

big_dict.values()

"""To retrieve a list of all the values and keys inside a dictionary, we use the **items()** method."""

big_dict.items()

"""To check the length (number of items) of a dictionary, we use the len() function."""

len(big_dict)

"""## 2.3. Data types

The keys in a dictionary should be unique and immutable.  
Keys can be:  
- numbers
- strings
- tuples
"""

dict_with_number_key = {1:'One',2:'Two',3:'Three'}
dict_with_number_key[1]

"""The values can be of **any type**, even other collections like lists."""

dict_with_list_values = {'fib':[0, 1, 1, 2, 3, 5, 8, 13, 21, 34],'prime':[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]}
dict_with_list_values['fib']

dict_with_list_values['fib'][3]

"""Dictionaries can contain mixed data types."""

mixed_dict = {
    'Country':'Germany',
    'EU':True,
    'Population':83000000,
    'Cities':['Berlin','Munich','Hamburg']}
mixed_dict

"""## 2.4. Update

To update a value in a dictionary, we need to access the value with a key and assign a new one.
"""

dict_to_update = {'Germany':'London','France':'Paris'}
dict_to_update

dict_to_update['Germany'] = 'Berlin'
dict_to_update

"""We can also update the value with the **update()** method."""

dict_to_update = {'Germany':'London','France':'Paris'}
dict_to_update.update({'Germany':'Berlin'})
dict_to_update

"""New entries to an existing dictionary can also be made using either approach."""

# reset the dictionary
dict_to_update = {'Germany':'Berlin','France':'Paris'}

dict_to_update['Spain'] = 'Madrid'
dict_to_update.update({'Italy': 'Rome', 'Poland': 'Warsaw'})
dict_to_update

"""## 2.5. Remove

The **pop()** method removes the item with specified key.
"""

dict_to_remove = {'Germany':'Berlin','France':'Paris'}
dict_to_remove

"""The **pop()** method also returns the removed value so we can save it to another variable if needed."""

x = dict_to_remove.pop('France')

dict_to_remove

x

"""The **del** keyword also removes the item with specified key."""

dict_to_delete = {1:'First',3:'Third'}
dict_to_delete

del dict_to_delete[3]
dict_to_delete

"""## 2.6. Exercises

### Exercise 11

Put these values in a `prices` dictionary:  
- banana: 4

- apple: 2

- orange: 1.5

- pear: 3
"""

# Show your skills!

prices = {'banana': 4, 'apple': 2, 'orange': 1.5, 'pear' : 3}

"""##### Hint"""

# _______ = {_______:4, _______:__, "orange":__, _______:__}

"""### Exercise 12

Add more values to the `prices` dictionary.

- lemon: 5000
- pasta: 3
"""

# Stay positive

prices.update({'lemon':5000,'pasta':3})
prices

"""##### Hint"""

# prices[_______] = _______
# _______["pasta"] = _______

"""### Exercise 13

Delete the item with the key `"pasta"` and store the value in the variable `deleted_value`.
"""

# Stay determined; your code will lead you to the solution.
deleted_value = prices.pop('pasta')
prices

"""##### Hint"""

# deleted_value = _______.pop(_______)

"""### Exercise 14

Update the value of the item with the key `"lemon"` to `5`.
"""

# You're the coding hero in this story

prices.update({'lemon' : 5})
prices

"""##### Hint"""

# prices[_______] = 5

"""# &nbsp;3. BONUS Tuples and Sets

## 3.1 Tuples
**Tuples** are very much like lists. The only difference is that tuples are unmutable. You will see what that means in a second. They are defined by regular parentheses `()` instead of square brackets `[]`.
"""

my_tuple = ("a", "b", "c", "d")
print(my_tuple)

"""Tuples are ordered. You can select items inside of a tuple by indexing with `[]`."""

my_tuple[2]

"""But you can not update the value of an element inside of a tuple. Trying to do so will result in a `TypeError`.


"""

my_tuple[2] = "e"

print(my_tuple[0])

"""## 3.2 Sets
**Sets** are another type of collections of items, just like lists and tuples. They have the following properties:

* They are not ordered.
* Since they are unordered, they lack indexing.
* They cannot contain duplicate items.
"""

my_set = {1, 2, 3, 4}

"""If you try to include a duplicate in a set, it will simply not get stored."""

my_fibonacci_set = {1, 1, 2, 3, 5}
print(my_fibonacci_set)

"""This characteristic makes them useful to extract unique values from other python collections. You can transform another collection into a set using the `set()` function:"""

# https://www.w3schools.com/python/ref_func_set.asp

price_list = [3.99, 2.5, 9.99, 1, 4.95,
              3, 2.5, 6, 8, 1, 9.99, 4,
              11.25, 14, 3.99, 4, 6, 1]
unique_prices = set(price_list)
print(unique_prices)

print(
    "There are", len(price_list), "prices listed, but only",
    len(unique_prices), "unique price values."
    )

"""## 3.3 Exercises

#### Exercise 15

Create a tuple with 10 elements and store it in a variable named `first_tuple`.
"""

# Celebrate each code snippet as a step toward victory

first_tuple = (1, 2, 3, 4, 5, 4, 3, 2, 1)
first_tuple

"""##### Hint"""

# _____ = (1, 2, 3, 4, 5, 4, 3, 2, 1)

"""#### Exercise 16

Using `[]`, select only the first 6 elements of the tuple you created and store them in a new variable named `second_tuple`.
"""

# Don't be afraid to experiment!

second_tuple = first_tuple[:6]
second_tuple

"""##### Hint"""

# second_tuple = _____[:6]

"""#### Exercise 17

Convert the `second_tuple` into a set and store it in a variable called `first_set`.
"""

# You're doing great!

first_set = set(second_tuple)
first_set

"""##### Hint"""

# first_set = set(_____)

"""#### Exercise 18

Can you select the first element of the `first_set`?
"""

# Stay persistent

print(first_set[0])

"""##### Hint"""

# No

"""#### Exercise 19

Below, you have a set with healthy ingredients and another one with vegan ingredients. Using [set methods you will find here](https://www.w3schools.com/python/python_ref_set.asp), print out a set with ingredients that are both healthy and vegan.
"""

healthy_food = {"apple", "salmon", "avocado", "seafood", "olive oil", "spinach", "yogurt"}
vegan_food = {"cookies", "apple", "avocado", "candy", "olive oil", "fake chicken", "spinach"}

# Get coding, and watch those problems turn into achievements.

healthy_and_vegan = healthy_food.intersection(vegan_food)
healthy_and_vegan

"""##### Hint"""

# vegan_healthy = _____.intersection(vegan_food)
# print(vegan_healthy)
