# -*- coding: utf-8 -*-
"""3-if-else.ipynb

Automatically generated by Colab.

# &nbsp;1. If/Else statements

> **_WARNING, VERY BAD JOKE!_**    
Once, a programmer's wife sent her husband to a grocery store to buy a loaf of bread.   
On his way out, his wife said, “Buy a loaf of bread. If they have eggs, get a dozen.”  
An hour later, the husband returned home with 12 loaves of bread. The wife got angry and asked, “Why did you get 12 loaves of bread?”.  
He replied, “Because they had eggs.”

Did you understand this bad joke? No? No worries, after you have learned about If and Else statements, you will understand it and realise that it's still not funny. :)

### 1.1 Is equal to

We will start with a simple question: **Is `x` equal to 2?**

To ask if something is equal in Python, we use `==`.
"""

# Assigning the value.
x = 2
x

# Asking if it is equal to 2.
x == 2

# Asking if it is equal to 3.
x == 3

"""### 1.2 If statement with a condition

Let's put the question (i.e. the condition) inside an `if` statement.
"""

# Assign a value to a variable.
x = 2
# Ask if condition is true.
if x == 2:
    # This will only be executed if the condition is true.
    print("x is indeed 2")

"""Let's see what happens if the condition is not True (i.e. if it is False)."""

x = 3
if x == 2:
    print("x is indeed 2")
    print("this is also part of the if statement")
print("this is outside the if statement")

"""Nothing happened because the condition was False. So the code inside the `if` statement is not True (False).

### 1.3 Indentation

Indentation refers to the spaces at the beginning of a code line. Python uses indentation to indicate a block of code.  
When we make an `if` statement, everything we want to be executed "inside" of it has to be indented from the statement.
"""

if 5 > 2:
  print("Five is greater than two!") # the empty space in front of the print() function is an indent.

"""### 1.4 Else statement

What if we also want something to happen when the condision is False?  
In those cases, we use the `else` statement. Everything inside the `else` statement will happen if the condition in the preceding `if` statement is not True.
"""

x = 3

if x == 2:
    print("x is indeed 2")
else:
    print("x is not 2")

"""### 1.5 Other logical conditions

You can question many other conditions in an `if` statement as long as these conditions give a result of True or False such as `>` (greater than).
"""

x = 3
y = 5

if x > y:
    print("x is higher than y")
else:
    print("x is lower or equal to y")

list_1 = ["kitty","puppy"]

if list_1.count("lamb") > 0:
    print("list_1 contains the element 'lamb'")
else:
    list_1.append("lamb")
    print("list_1 didn't contain the element 'lamb', so we added it")
    print(list_1)

"""Python supports the usual logical conditions from mathematics:

- Equals: a == b
- Not Equals: a != b
- Less than: a < b
- Less than or equal to: a <= b
- Greater than: a > b
- Greater than or equal to: a >= b

### 1.6 Elif statement

Sometimes, we want to try multiple conditions and perform different actions for each.  
It is like saying "if the previous conditions are not true, try this one".

For that, we use the `elif` statement.
"""

x = "text"

if x == "blue":
    print("x is blue")
elif x == "red":
    print("x is red")
elif x == "green":
    print("x is green")
else:
    print("x is neither blue, red or green")

"""### 1.7 AND and OR

One `if` statement can have multiple conditions chained with special keywords like `AND` or `OR`.
"""

x = 2
y = 3

if x == 2 and y==3:
    print("Both statements are True.")

"""This table shows the expected outcomes of conditions chained with `AND`.

| **AND**   | **True** | **False** |
|-----------|----------|-----------|
| **True**  | True     | False     |
| **False** | False    | False     |
"""

x = 2
y = 5
z = 4

if (x > 5 or y==3) and z==4:
    print("One or both of the statements are True.")

"""This table shows the expected outcomes of conditions chained with `OR`.

| **OR**    | **True** | **False** |
|-----------|----------|-----------|
| **True**  | True     | True      |
| **False** | True     | False     |

### 1.8 input() function

One extra thing that might come in handy is the input from a user.  
Sometimes, we want to ask a user to input some information and use it later in our code.  
For this, we use the `input()` function.
"""

x = input("Choose a number from 1-100 and hit ENTER. ")

print(f"You have chosen the number: {x}")

"""This might seem familiar if you've ever installed something using the command line."""

x = input("Do you want to proceed? [y/n] ")

if x == "y":
    print("proceeding with the execution")
elif x == "n":
    print("not proceeding with the execution")
else:
    print("you are only allowed to enter y or n")

"""## Exercises

### Exercise 1

Print "condition is true" if x is greater than or equal to y.
"""

x = 3
y = 1

# Don't be afraid to be wrong!

if x >= y:
  print("condition is true")
else:
  print("condition is false")

"""##### Hint"""

# _____(x ___ y):
#     print("True")

"""### Exercise 2

Print "x is not equal to y" if x is not equal to y,  
print "x is equal to y" if x is equal to y.
"""

x=5
y=5

# Coding is a journey!

if x!=y:
  print("x is not equal to y")
else:
  print("x is equal to y")

"""##### Hint"""

# if(x __ y):
#     print("x is not equal to y")
# else:
#     print("x is equal to y")

"""### Exercise 3

Write an `if` statement that asks for the user's name using the `input()` function.  
If the name is "Bond", make it print "Welcome on board 007."  
Otherwise, make it print "Good morning NAME". (Replace NAME with the user's name).
"""

# Code with confidence!

"""##### Hint"""

# name = _____()
# if name _____ "Bond":
#     print("Welcome on board 007")
# else:
#     print(f"Good morning _____")

"""### Exercise 4

Print the results of the following:
 - If x is greater than y, subtract y from x.
 - If x is smaller than y, add x to y.
 - If x is equal to y, multiply x by y.
"""

x=3
y=3

# You've got this!

if x > y:
  print(x-y)
elif x < y:
  print (x + y)
else:
  print(x * y)

"""##### Hint"""

# _____ x > y:
#     print(x - y)
# elif x _____ y:
#     print(y + x)
# _____
#     print(x * y)

"""### Exercise 5

Use if statements to find which value is the biggest one and print "The biggest value is VALUE.".
BONUS: Check out the solution with nested statements.
"""

x=83
y=45
z=45

# Don't be afraid to experiment!

if x >= y and x >= z:
  print(f"The biggest value is {x}")
elif y >= x and y >= z:
  print(f"The biggest value is {y}")
else:
  print(f"The biggest value is {z}")

"""##### Hint"""

# if _____ >= y _____ x >= z:
#     print(f"The biggest value is {x}")
# _____ y >= x and _____ >= z:
#     print(f"The biggest value is {_____}")
# else:
#     print(f"The biggest value is {z}")
