# -*- coding: utf-8 -*-
"""4_intro_to_apis.ipynb

Automatically generated by Colab.

# Introduction to APIs

## 1.&nbsp;Recap: lists and dictionaries

### 1.1&nbsp;Lists

A list starts and ends with square brackets `[]` and contains elements that are separated with a comma `,`.

Here are a few examples:
"""

# Empty list.
empty_list = []
empty_list

# List containing numbers.
list_with_numbers = [2, 64, 3.5, 7392, -5]
list_with_numbers

# List containing other lists as elements.
list_of_lists = [[1, 2, 3], ["apples", 280], [-1, True, 4.5]]
list_of_lists

"""You can access the individual elements inside the list by using their index."""

# Get the first element from the list_with_numbers.
list_with_numbers[0]

# Get the second element from the list_of_lists.
list_of_lists[1]

# Get the first element from the second list inside the list of lists.
list_of_lists[1][0]

"""### 1.2&nbsp;Dictionaries

A dictionary starts and ends with curly brackets `{}` and contains key-value pairs which are separated by a comma `,`.

Here are a few examples:
"""

# Empty dictionary.
empty_dictionary = {}
empty_dictionary

# Simple dictionary.
simple_dictionary = {"surname": "Duck", "name": "Donald"}
simple_dictionary

"""You can get a list with all the keys of the dictionary using `.keys()`."""

# Show the keys inside the dictionary.
simple_dictionary.keys()

"""You can access the individual values inside the dictionary by using the name of the key."""

simple_dictionary

# Get the value of the key "name".
simple_dictionary["name"]

# Nested dictionary that contains another dictionary as one of the values.
nested_dictionary = {"surname": "Holmes", "name": "Sherlock", "address": {"street": "Baker Street 221b", "city": "London"}}
nested_dictionary

# This also works with nested dictionaries.
nested_dictionary["address"]

# Combinations are also possible.
nested_dictionary["address"].keys()

nested_dictionary["address"]["street"]

"""## 2.&nbsp;Requests

The requests library is the de facto standard for making HTTP requests in Python. It abstracts the complexities of making requests behind a beautiful, simple API so that you can focus on interacting with services and consuming data in your application.

https://requests.readthedocs.io/en/latest/

When we make a request, we get a `requests.Response` object in return. The `requests.Response` object contains the server's response to the HTTP request. The response itself consists of several parts such as the content, the text or the status code.

The status code is a number that tells us whether we received the information we wanted or not. If you get a number that you don't understand, these cats will help you: https://http.cat/.

More often than not you'll receive one of these status codes:

- `200`: Success!

- `401`: Unauthorized client error status: lack of valid authentication credentials

- `403`: The server understood the request but refuses to authorize it
"""

import pandas as pd
import requests

"""Make a request to the website of The New York Times."""

# The response from the website is stored inside the variable 'nyt'.
nyt = requests.get("https://www.nytimes.com/")
nyt

# Get the status code from the response.
nyt.status_code

# Get the text from the response.
nyt.text

"""Make a request to the website of WBS Coding School."""

# The response from the website is stored inside the variable 'wbscs'.
wbscs = requests.get("https://www.wbscodingschool.com/")
wbscs

wbscs.status_code

wbscs.text

"""## 3.&nbsp;JSON

### 3.1&nbsp;Viewing the JSON

https://docs.python.org/3/library/json.html

Since its inception, JSON has quickly become the de facto standard for information exchange. JSON supports primitive types, like strings and numbers, as well as nested lists and objects. It looks like nested python dictionaries:

```
{"firstname": "Harry",
 "lastname": "Noah",
 "city": "Berlin",
 "dogs": [{"name": "rover",
   "breed": "labrador"},
   {"name": "pip",
   "breed": "spaniel"}],
 "cars": "none"}
```

Send a `get` request to the International Space Station API to know where the ISS is right now.

You can find the documentation here: http://open-notify.org/Open-Notify-API/ISS-Location-Now/.
"""

# Make a request to the ISS API and store the response in `iss`.
iss = requests.get("http://api.open-notify.org/iss-now.json")

# Check the response.
iss

# Have a look at the text of the response.
text = iss.text
type(text)

# Finally: view the response as a JSON.
iss.json()

"""### 3.2&nbsp;Accessing the data in the JSON

Now that we know
- what an API is,
- how to request information from one (requests),
- how the information will be delivered to us (JSON):

Let's see how we can use this information. We will first look at how we can access particular values within the JSON.

The following API returns the current sunrise and sunset times for a specified location. You can check out the website with the documentation here: https://sunrisesunset.io/api/.

The structure of the url to the API is determined by the provider of the API and usually consists of several parts:

* A first part that leads to the specific API and is the same in every call.
  
  Example: `api.sunrise-sunset.org/json?`

* A mandatory part in which we define certain parameters in a pre-defined format.

  Example: the API requires both the latitude and the longitude of the location in decimal degrees `lat=36.7201600` and `lng=-4.4203400`.

* An optional part in which we can define more parameters in a pre-defined format.

  Example: the date can be specified in YYYY-MM-DD format `date=1990-05-22`, or in a relative format, such as “today” and “tomorrow”. If no date is specified, the default date will be today.
"""

# Get the sunrise and sunset times for Berlin.
# First define the latitude, longitude and date.
latitude = 52.52
longitude = 13.24
date = "2023-01-01"

# Combine the different parts from above to create one url.
sun = requests.get(f"https://api.sunrise-sunset.org/json?lat={latitude}&lng={longitude}&date={date}")
sun_json = sun.json()
sun_json

"""Let's access a few values from the JSON.

Notice that the JSON is enclosed in curly brackets `{}`. This means that it is a dictionary and we can access the values by calling their respecitve keys.
"""

# Which are the keys?
sun_json.keys()

# What is the value of the results key?
sun_json["results"]

# What is the time of the sunrise?
sun_json["results"]["sunrise"]

"""### 3.3&nbsp; Transforming a JSON into a DataFrame

#### 3.3.1&nbsp;Option 1: pd.DataFrame()
"""

sun_json

# Transform JSON into a DataFrame.
sun_df = pd.DataFrame(sun_json)
sun_df

"""This returns a DataFrame, and we could even set the indices using `.reset_index()`.

Still, we would prefer to have only a single row for a single day, with all the keys from the two different levels as column titles.

#### 3.3.2&nbsp;Option 2: pd.json_normalize()
Another way to handle nested dictionaries is by using json_normalize().

https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html
"""

# Transform JSON into a DataFrame.
sun_norm = pd.json_normalize(sun_json)
sun_norm

"""SUCCESS!

## 4.&nbsp; Creating DataFrames using for loops, lists and dictionaries

Often, there are several elements of the same type and structure inside one JSON. Let's have a look at an example and ask for the times for 3 days.
"""

# Define the latitude, longitude and 3 days.
latitude = 52.52
longitude = 13.24
dates = ["yesterday", "today", "tomorrow"]

# Get the JSON for the first value inside the date lists (= yesterday).
sun = requests.get(f"https://api.sunrise-sunset.org/json?lat={latitude}&lng={longitude}&date={dates[2]}")
sun_json = sun.json()
sun_json

"""To get the times for all three days, we will use a for loop. It requests the data for yesterday first, then for today, then for tomorrow, and adds them as separate elements to a list.

The resulting list looks much like the JSON you get from APIs that provide the same type of data multiple times inside a single JSON. This step will therefore usually not be necessary because your initial JSON will already have a comparable structure.

If you like to review for loops and/or the range, here is some useful information:

- https://www.w3schools.com/python/python_for_loops.asp

- https://www.w3schools.com/python/ref_func_range.asp
"""

# Initialize an empty list to store all the JSONs.
times = []
# Loop over the elements in the date list.
# Request data from the API for each of the date elements.
# Save the returned JSON in the time list.
for date in dates:
  times.append(requests.get(f"https://api.sunrise-sunset.org/json?lat={latitude}&lng={longitude}&date={date}").json())

times

"""If we only want to select certain parts of the JSON:
- Option 1: transform the entire JSON into a DataFrame and drop the rest.
- Option 2: Use a for loop to extract only the required information. This is what we will look into as the next step.

### 4.1&nbsp;Write a for loop

Creating a for loop is usually an iterative process.

First, we select one value from our JSON that we would like to have in our final DataFrame. Let's start with yesterday's sunrise time.

>To access values inside nested lists and dictionaries, we need to apply the [Matryoshka doll](https://en.wikipedia.org/wiki/Matryoshka_doll) principle. This means that we will need to access the most outer dictionary/list first, then the next one inside, then the next etc.
"""

# First select the element of the list that contains yesterday's data.
# Then select the keys that navigate you to the sunrise time.
times[0]["results"]["sunrise"]

yesterday_sunrise = times[0]["results"]["sunrise"]

"""Using this code, it is easy to get the sunrise time of today and tomorrow, too. Just change the value to the index of the day you're interested in."""

times[1]["results"]["sunrise"], times[2]["results"]["sunrise"]

"""Now let's build a for loop with the code we have prepared:"""

# Create an empty list which will be filled with the sunrise times.
sunrise = []

# Iterate over the 3 dictionaries inside the times list.
for time in times:
  # For each day, get the sunrise time and append it to the sunrise list.
  sunrise.append(time["results"]["sunrise"])

# Let's have a look at the sunrise list.
sunrise

"""SUCCESS!

Once this loop works with one value, more can be added. Let's add the sunset time and the day length.
"""

# Create an empty list for each of the values.
sunrise = []
sunset = []
day_length = []

# Iterate over the 3 dictionaries inside the times list.
for time in times:
  # For each day, get the sunrise time and append it to the sunrise list.
  sunrise.append(time["results"]["sunrise"])
  # For each day, get the sunset time and append it to the sunset list.
  sunset.append(time["results"]["sunset"])
  # For each day, get the day length and append it to the day length list.
  day_length.append(time["results"]["day_length"])

"""Let's have a look at all these lists."""

sunrise, sunset, day_length

"""### 4.2&nbsp;Create a DataFrame using lists

As a final step, we want to merge these lists into a DataFrame.
"""

# Zip the different lists, and add the column labels at the end.
times_df = pd.DataFrame(list(zip(sunrise, sunset, day_length)), columns=["Sunrise", "Sunset", "Day_length"])
times_df

"""### 4.3&nbsp;Create a DataFrame using dictionaries

Alternatively, a dataframe can be created from a dictionary, using the lists from the for loop above.
"""

# Pass a dictionary inside pd.DataFrame().
# Its keys are the column labels.
# Its values are the lists containing the data to become the columns of your DataFrame.
# We can even easily add the list containing the dates.
times_df_dictionary = pd.DataFrame({"Day": dates,
                                    "Sunrise": sunrise,
                                    "Sunset": sunset,
                                    "Day length": day_length}
                                   )
times_df_dictionary

"""Another option is to create the dictionary first, and then use the for loop to fill its values."""

# Create an empty list for each of the values.
times_dictionary = {"Sunrise": [],
                    "Sunset": [],
                    "Day_length": []}

# Iterate over the 3 dictionaries inside the times list.
for time in times:
  # For each day, get the sunrise time and append it to the sunrise list.
  times_dictionary["Sunrise"].append(time["results"]["sunrise"])
  # For each day, get the sunset time and append it to the sunset list.
  times_dictionary["Sunset"].append(time["results"]["sunset"])
  # For each day, get the day length and append it to the day length list.
  times_dictionary["Day_length"].append(time["results"]["day_length"])

times_dictionary

# Create a DataFrame from the dictionary.
times_dictionary_df = pd.DataFrame(times_dictionary)
times_dictionary_df

"""## 5.&nbsp;APIs with keys

Some APIs restrict access to their data in the sense that users need to register beforehand. Upon registration, users receive an API key that is linked to their account. This has two main consequences:

* The url used to request the data needs to contain the API key.
* The API can track the number and type of requests made. This enables APIs to limit the number of requests per account within a certain timeframe.

Let's have a look at how this works with an API that provides useful statistics about many cities around the world: https://api-ninjas.com/api/city

There are a few parameters available to filter the cities returned. We will use these:
* name (optional) - name of city.
* country (optional) - country filter. Must be an ISO-3166 alpha-2 country code (e.g. US).
* min_population (optional) - minimum city population.
* limit (optional) - How many results to return. Must be between 1 and 30. Default is 1.

### 5.1&nbsp;Accessing the data
"""

# Define the parameters to be passed into the url.
country = "DE"
city = "Berlin"
API_key = "ABC"

# Reference the parameters in the url.
city_request = requests.get(f"https://api.api-ninjas.com/v1/city?name={city}&country={country}", headers={'X-Api-Key': API_key})
city_json = city_request.json()
city_json

# Or define the sections that will together form the url.
url = "https://api.api-ninjas.com/v1/city"
header={"X-Api-Key": "ABC"}
querystring = {"country" : "DE", "name":"Berlin"}

# Reference the sections in the request.
city_request = requests.request("GET", url, headers=header, params=querystring)
city_json = city_request.json()
city_json

# Creating a for loop that will go over Germany's 5 largest cities, retrieving API info for each one
german_cities = ['Berlin', 'Hamburg', 'Frankfurt', 'Munich', 'Cologne']
cities_json = []     # Empty list, on each iteration we will add the current API response to it

for german_city in german_cities:
  url = "https://api.api-ninjas.com/v1/city"
  header={"X-Api-Key": "ABC"}
  querystring = {"country" : "DE", "name" : german_city}   # Passing the current iteration city name as the value in the 'querystring' dictionary
  city_request = requests.request("GET", url, headers=header, params=querystring)
  city_json = city_request.json()
  cities_json += city_json    # Adding current iteration response to list of responses from all cities together, using '+' to add lists to one another

cities_json

"""### 5.2&nbsp;Transforming the data

Create a dataframe that contains the information from the JSON.
"""

cities_df = pd.DataFrame(cities_json)
cities_df

"""Drop the column `is_capital`."""

cities_df = cities_df.drop(["is_capital"], axis=1)

"""Change the data type of the column `population` to float."""

# Check the data type of all columns first.
cities_df.info()

# Change the data type.
cities_df['population'] = pd.to_numeric(cities_df['population'], downcast='float')

# Check the data type of all columns again.
cities_df.info()

"""Create a new column which combines the `city` and `country` columns. The values in the new column are unique. This is handy for potential later usage e.g. as a primary key in SQL."""

cities_df["name_country"] = cities_df["name"] + ", " + cities_df["country"]

cities_df
