# -*- coding: utf-8 -*-
"""4-loops.ipynb

Automatically generated by Colab.

# 1.&nbsp; Why loops?
"""

ingredients = ["milk", "sugar", "vanilla extract", "dough", "chocolate"]

"""Printing all the elements of a list without a loop."""

print(ingredients[0])
print(ingredients[1])
print(ingredients[2])
print(ingredients[3])
print(ingredients[4])

"""Printing elements of a list with a loop."""

for ingredient in ingredients:
    print(ingredient)

"""Now imagine if we had 1000, 10 000 or even more elements in a list... That's why **loops** are very useful.

# 2.&nbsp; `For` loops

## 2.1.&nbsp; General structure of a `for` loop
"""

for <iterative variable> in <collection>:
  <action>

"""- A `for` keyword indicates the start of a for loop.
- A `<iterative variable>` that is used to represent the value of the element in the collection the loop is currently on.
- An `in` keyword separates the iterative variable from the collection used for iteration.
- A `<collection>` to loop over (list, dictionary...).
- An `<action>` to do something on each iteration of the loop.

## 2.2.&nbsp; Looping through lists

If we want to access each element of the list and do something with it, we will **loop** through a list.
"""

names_list = ["Justine", "Anabel", "Karl"]

for name in names_list:
    print("Hello " + name + "!")

"""Here, the word `name` could really be anything. It is just a placeholder that takes the value of each element in the for loop in every successive iteration, until the loop reaches the end of the list. Using a different word than `name` does not change the result."""

for dinosaur in names_list:
    print("Hello " + dinosaur + "!")

"""If we wanted to store the resulting transformations of our loop in a new list, we would define an empty list first, and then `append()` all the elements as we iterate through the loop."""

greetings = []

for name in names_list:
    greetings.append("Hello " + name + "!")

greetings

"""## 2.3.&nbsp; Looping through a string

Looping through a string is like looping through a list of characters of a string ( "BLIMEY" -> ["B", "L", "I", "M", "E", "Y"] ).
"""

for character in "ALPHABET":
    print("New iteration")
    print(character)

"""## 2.4.&nbsp; Looping through dictionaries

Looping through a dictionary, we can access each key.
"""

results_of_test = {"Mary":68,"Jose":78,"Carl":56,"Dylan":91}

for student in results_of_test:
    print(f"{student} scored {results_of_test[student]} points.")

"""## 2.5.&nbsp; Looping inside a range

When you loop through collections like lists or dictionaries, the for loop will iterate as many times as there are elements inside the collection.

In some cases, however, you will not want to loop through a defined collection you already have. Instead, you might just need to repeat something several times.
For that, you only need to know how many times to iterate and the `range()` function will create a sequence of numbers that coincides with your needs.

`range(5)` returns a sequence of numbers, starting from 0 and ending at 5 where 5 is not included.
"""

for i in range(5):
    print(i)

"""`range(2,8)` returns a sequence of numbers, starting from 2 and ending at 8 where 8 is not included."""

for i in range(2,8):
    print(i)

"""`range(10,55,5)` returns a sequence of numbers, starting from 10 and ending at 55 where 55 is not included. The step between the numbers is no longer 1 but 5."""

for i in range(10,55,5):
    print(i)

"""# 3.&nbsp; `While` loops

In python, we use `for` loops to iterate through something.

There are also `while` loops which iterate as long as a condition is true.
"""

number = 10
while number > 0:
    print(number)
    number = number - 1

"""The above loop will continue looping as long as the number variable is greater than 0.

# 4.&nbsp; Infinite loop

A loop that never terminates is called an infinite loop.
These are very dangerous for our code because they will make our program run forever and thus consume all of your computer’s resources.
"""

# This is an infinite loop.
# If you run it, you need to force your kernel to stop by pressing the "stop" button.

# total = 1
# while True:
#   print(f"This has printed {total} times")
#   total += 1

"""# 5.&nbsp; Control flow statements
When using either a for loop or a while loop, we have a couple of valuable options to manage the flow of information: "continue" and "break."

## 5.1.&nbsp; Break
`break` does exactly what it says, it breaks a loop. Let's copy and moderate the infinite loop from the previous paragraph and 'fix' it with a break.
"""

numbers_list = [2,4,6,8]
for number in numbers_list:
    numbers_list.append(number+2)
    if len(numbers_list) == 20:
        print(numbers_list)
        break

"""Now our loop is not infinite anymore because it will break (stop) when the `if` condition is True (i.e. when the number of elements is equal to 20).

## 5.2.&nbsp; Continue
If we want the loop to skip some elements, we can write the `continue` statement. Whenever a loop reaches the continue statement, it will jump straight into the next iteration.
"""

names = ["Anna","Lanne","Hanne","Yanne"]
new_list = []

for name in names:
    if name.startswith("A"):
        continue
    new_list.append(name)

print(new_list)

"""The new list now consists only of names that didn't start with the letter A. This is because as soon as the name Anna was reached, the continue statement in the loop jumped to the next iteration.

# 6.&nbsp; Nested loops
You can nest any number of loops.
"""

teams_dict = {"Green team": ["Viraj","Eva","Leon"],
              "Blue team":["Sarrah","Frida","Tim"],
              "Yellow team":["Karl","Ali","Maria"]}

# First loop loops through 3 teams.
for team in teams_dict:
    # The variable team will change like this: 1st iteration: Green team, 2nd iteration: Blue team...
    print(team+":")
    # Second loop loops through list of names for each team from the first loop.
    for name in teams_dict[team]:
        print(name)

"""# 7.&nbsp; Exercises

#### Exercise 1

Create a list named `lower_names` and fill it with your favourite actors. Include name and surname, all in lowercase (like `john doe`).
Then, create a new list `capital_names` with both the names and surnames capitalized (like `John Doe`), by iterating through the first list with a `for` loop.
"""

# It's okay to make mistakes!

lower_names = ["harry potter", "hermione granger", "ron weasely", "albus dumbledore", "luna lovegood"]
capital_names = []
for name in lower_names:
  capital_names.append(name.title())
capital_names

"""##### Hint"""

# lower_names = ["_____ _____","_____ _____","_____ _____","_____ _____","_____ _____","_____ _____"]
# capital_names = []
# _____ name in _____:
#     capital_names._____(name._____())

"""#### Exercise 2

Use the `capital_names` list from the previous exercise and print out only the ones that start with "A" or "J".
"""

# We're all learning here!

list_with_a_j = []

for name in capital_names:
  if name.startswith(("A","J")):
    list_with_a_j.append(name)
list_with_a_j

"""##### Hint"""

# for name in _____:
#     if _____.startswith("A") or name._____("J"):
#         print(_____)

"""#### Exercise 3

You are given a list of names. Loop through the list and print "Hello `name`!" if a name starts with "A". If not, print "Bye `name`!".
"""

names = ["Justine","Amabel","Karl","Anna","Lina","Sergei","Wang","Aurora"]

# Coding is your superpower; use it to conquer the challenge

for name in names:
  if name.startswith("A"):
    print(f"Hello {name}!")
  else:
    print(f"Bye {name}!")

"""##### Hint"""

# for _____ in names:
#     if name._____("A"):
#         print("Hello "+_____+"!")
#     _____:
#         print("Bye "+_____+"!")

"""#### Exercise 4

Copy the code from last exercise and add a text that gets printed after each iteration of the loop, so it is clearer what"s going on. ("Next iteration incoming...")
"""

# Write code with confidence

for name in names:
  if name.startswith("A"):
    print(f"Hello {name}!")
  else:
    print(f"Bye {name}!")
  print("Next iteration incoming..")

"""##### Hint"""

# for _____ in names:
#     if name._____("A"):
#         print("Hello "+_____+"!")
#     _____:
#         print("Bye "+_____+"!")
#     _____("Next iteration incoming...")

"""#### Exercise 5

In the previous code, the "next iteration incoming..." text gets printed also for the last iteration, which might be confusing for whoever reads the output of this code. Change the code so that this text gets printed in all except the last iteration.
"""

# Stay curious and keep coding

count = 1
for name in names:
  if name.startswith("A"):
    print(f"Hello {name}!")
  else:
    print(f"Bye {name}!")
  if count != len(names):
    print("Next iteration incoming..")
  count+=1

"""##### Hint"""

# count = _____
# for _____ in names:
#     if name._____('A'):
#         print('Hello '+_____+'!')
#     _____:
#         print('Bye '+_____+'!')
#     if _____ != len(names):
#         print('Next iterartion incoming...')
#     _____ += 1

"""#### Exercise 6

You are given a list of numbers. Looping through the list, sum all the numbers and print the result.
"""

numbers = [23,45,12,10,25]

# Embrace the challenge

total = 0
for num in numbers:
  total += num
print(total)

"""##### Hint"""

# total = 0
# for number in _____:
#     _____ = _____ number
# print(_____)

"""#### Exercise 7

Create a simple calculator for additions!
Repeatedly ask the user to enter numbers. Each time that the user provides input, this input is first converted to float and then added to a variable `total` (which should start from 0).
When the user enters "add", the loop stops and the running total is printed out.
"""

# Bugs are just detours on the road to success; keep coding!

total = 0
while True:
  print("Enter a number or write 'add' to sum all the inputs.")
  number = input()
  if number == 'add':
    break
  else:
    total += float(number)
print(total)

"""##### Hint"""

# total = 0
# while True:
#     print("Enter number or write 'add' to sum all previous inputs.")
#     _____ = input()
#     if number == _____:
#         break
#     else:
#         _____ += float(_____)
# print(_____)

"""# 8.&nbsp; Bonus exercises


"""

# some lists to work with

car_brands = ["BMW", "Volkswagen", "Mercedes", "Ford", "Apple", "Toyota",
              "Tesla", "Kia", "Porsche", "Mazda", "Honda", "Jaguar",
              "Mitsubishi", "Audi", "Bentley", "Bugatti", "Chrysler"]

fibonacci = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 53, 89, 144]

characters = [["Harry", "Hermione", "Ron"],
              ["Daenerys Targaryen", "Jon Snow", "Tyrion Lannister",
               "Cercei Lannister", "Arya Stark", "Sansa Stark"],
              ["Aragorn", "Gandalf", "Frodo", "Legolas", "Gollum", "Gimli"],
              ["Walter White", "Jesse Pinkman", "Gus Fring"]
             ]

sex_and_the_city = ["Carrie", "Samantha", "Charlotte", "Miranda"]

numbers = [1, 51, 59, 2, 95, 25, 28, 67, 14, 63, 84, 33, 56, 31, 54, 97, 77,
            98, 46, 84, 6, 66, 86, 77, 69, 19, 77, 7, 76, 19, 59, 77, 28, 34,
            94, 4, 45, 95, 41, 66, 5, 38, 35, 57, 84, 38, 94, 65, 45, 80, 83,
            22, 12, 100, 52, 55, 31, 69, 29, 67, 4, 39, 87, 49, 81, 82, 96, 4,
            85, 62, 90, 72, 70, 26, 29, 63, 48, 94, 58, 9, 49, 79, 33, 63, 41,
            13, 90, 37, 31, 3, 11, 54, 56, 72, 91, 97, 2, 83, 82, 6]

"""#### Exercise 8

Implement the for loop that greets people for the `characters` list you used in the previous exercises. For now, do not include any condition —just say hello to every character. What do you need to do to iterate through lists inside a list?
"""

# You're on the right track; keep coding and stay determined.

for shows in characters:
  for character in shows:
    print(f"Hello {character}!")

"""##### Hint"""

# for _____ in characters:
#     for character in _____:
#         print("Hello " + character)

"""#### Exercise 9

Tweak the code of the previous exercise to greet characters based on these conditions:

- If their name is composed of two words (Name Surname), the greeting should be "Hello Name, from the house of Surname".

- If their first (or only) name is shorter than 6 characters, the greeting should replicate the last letter of the name as many times as needed until it reaches 6 characters.
"""

# Solve it with code!


for shows in characters:
  for character in shows:
    split_name = character.split(" ")
    fname = split_name[0]
    # we don't define the lname here because we don't know yet which ones have only one name or two names.
    # So you can't access it right now
    while len(fname) < 6:
      fname += fname[-1]
    if len(split_name) == 1:
      print(f"Hello {fname}!")
    else:
      lname = split_name[1] # now that we know there are two names, we assign the variable
      print(f"Hello {fname}, from the house of {lname}")

"""##### Hint"""

# for _____ in characters:
#     for character in _____:
#         list_of_names = _____.split(" ")
#         first_name = _________
#         while _____(first_name) < _:
#             first_name += first_name[_]
#         if len(_____) == 1:
#             print(f"Hello {first_name}!")
#         else:
#             print(f"Hello {first_name}, from the house of {list_of_names[_]}")
