# -*- coding: utf-8 -*-
"""data51-weather-collaborative-solution.ipynb

Automatically generated by Colab.

"""

API_key = 'ABC'
lat = 52.52
lon=13.41
api_endpoint = f'https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={API_key}&units=metric'

api_endpoint

import requests
response = requests.get(api_endpoint)

response.status_code

weather_data = response.json()

import pandas as pd
pd.json_normalize(weather_data['list'])

weather_data['list'][0].get('main', 'default value')

import pandas as pd

pd.DataFrame({'temp':[], 'humidity':[], 'rain':[], 'snow':[]})

data_for_df = {'temp':[], 'humidity':[], 'rain':[], 'snow':[]}

{'name':'Ahmed',
 'City':'Ottawa'}.get('jaslfa', 0)



for time_slot in weather_data['list']:
    data_for_df['temp'].append(time_slot['main']['temp'])
    data_for_df['humidity'].append(time_slot['main']['humidity'])
    data_for_df['rain'].append(time_slot['rain']['3h'] if 'rain' in time_slot else 0)
    data_for_df['snow'].append(time_slot.get('snow', {}).get('3h', 0))

pd.DataFrame(data_for_df )

from datetime import datetime
import pytz
datetime.now(pytz.timezone('Europe/Berlin')).strftime('%Y-%m-%d %H:%M:%S')

def get_city_weather(cities, latitudes,longitudes):
    #for city, lat, lon in zip(cities, latitudes, longitudes):
    data_for_df = {'city':[],'temp':[], 'humidity':[], 'rain':[], 'snow':[], 'time_retrieved':[]}
    for i in range(len(latitudes)):
        lat = latitudes[i]
        lon = longitudes[i]
        city = cities[i]
        API_key = 'ABC'

        api_endpoint = f'https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={API_key}&units=metric'

        response = requests.get(api_endpoint)
        weather_data = response.json()
        for time_slot in weather_data['list']:
            data_for_df['city'].append(city)
            data_for_df['temp'].append(time_slot['main']['temp'])
            data_for_df['humidity'].append(time_slot['main']['humidity'])
            data_for_df['rain'].append(time_slot['rain']['3h'] if 'rain' in time_slot else 0)
            data_for_df['snow'].append(time_slot.get('snow', {}).get('3h', 0))
            data_for_df['time_retrieved'].append(datetime.now(pytz.timezone('Europe/Berlin')).strftime('%Y-%m-%d %H:%M:%S'))
    return pd.DataFrame(data_for_df)

get_city_weather(['Berlin', 'Paris', 'London'], [52.52, 48.85, 51.50], [13.41, 2.35, -0.12])

get_city_weather(['Berlin'], [52.52], [13.41])

for number,letter, something in zip([1,2,3,4],['a','b','c','d'], ['x','y','z','w']):
    print('the number is ',number, 'the letter is ', letter, 'the something is ', something)

connection_string = 'mysql+pymysql://root:123456@localhost:3306/gans'

cities_db = pd.read_sql('cities', con=connection_string)
cities_db

weather_df = get_city_weather(cities_db['name'], cities_db['latitude'], cities_db['longitude'])
weather_df

weather_df.to_sql("weather", con=connection_string, if_exists='append', index=False)
