# -*- coding: utf-8 -*-
"""Pandas-2_Warmup__Indexing_Data_Frames.ipynb

Automatically generated by Colab.

#### Exercise 1: Turn the following dictionary into a pandas data frame and save it to a variable called `employees_df`
"""

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Claire', 'David', 'Emma'],
    'Age': [25, 30, 22, 28, 35],
    'Salary': [50000, 60000, 45000, 70000, 80000],
    'Contract': ['probation', 'unlimited', '6 months', '3 years', 'unlimited']
}

# Your code here

employees_df = pd.DataFrame(data, columns=['Name', 'Age', 'Salary', 'Contract'])
employees_df

"""##### Hint:

You can use `pd.DataFrame()` to create data frames out of other data types that fit the tabluar shape. <br>(Remember you'll have to import pandas first!)

#### Exercise 2: Grab the `'Salary'` column and store it in a variable called `salary_series`. Do this *without* using `.loc` or `.iloc`
"""

# Your code here

salary_series = employees_df['Salary']
salary_series

"""##### Hint:

You can grab a column of a data frame similarly to how you would if it were a dictionary: `df['columns_name']`

#### Exercise 3: Use the describe method to get summary statistics about `salary_series`
"""

# Your code here

salary_series.describe()

"""##### Hint:

`.describe()` will give you summary statistics about numerical series or data frames.<br><br>
Methods come after the variable with the syntax `variable.method()`

#### Exercise 4: Make the `Name` column the index of the employees data frame
"""

# Your code here

employees_df = employees_df.set_index('Name')
employees_df

"""##### Hint:

You can use `df.set_index('column_name')` to make one of the columns the index. (Remember this won't automatically save!)

#### Exercise 5: Now that the name is the index, use `.loc` to access Alice's salary
"""

# Your code here

employees_df.loc['Alice','Salary']

"""##### Hint:

`df.loc[rows, columns]` will select that subset of rows and columns from the data frame

#### Bonus: Use `.loc` to create a new data frame with just Alice and Emma and just their salaries and contracts and assign it to a variable called `new_df`
"""

# Your code here

new_df = employees_df.loc[['Alice','Emma'],['Salary','Contract']]
new_df

"""##### Hint:

`df.loc[rows, columns]` will select that subset of rows and columns from the data frame
"""
