# -*- coding: utf-8 -*-
"""Pandas-1_Warmup__Iterables_Refresher.ipynb

Automatically generated by Colab.

#### Exercise 1: Create a list with the numbers `1`, `2`, `3`, `4`, and `5` in it and save it in a variable called `my_list`
"""

# Your code here

my_list = [1, 2, 3, 4, 5]

"""##### Hint:

Lists are written by placing items between square brackets with the items separated by commas. <br><br>
For instance, `['item_1', 'item_2', 'item_3']`

#### Exercise 2: Select the last item from your list from the previous step using indexing
"""

# Your code here

last = my_list[-1]
print(last)

"""##### Hint:

You can grab specific items from lists using their index: the position the item has in the list. You do this by putting the index in brackets right after the list. (Remember indexes start at 0!)<br><br>
For instance, `[10, 14, 72, 34][1]` will return `14` because this is the second item in the list being indexed.

#### Exercise 3: Take a slice of your list, grabbing the last 3 items
"""

# Your code here

slice_my_list = my_list[:-3]
print(slice_my_list)

"""##### Hint:

You can grab several items from a list at once using slices. Here you provide a start and end index and it will return all the items between. You can do this by again putting the index in brackets, but now you put a colon between the start and end index. The slice will include the element corresponding with the start index but exclude the item corresponding with the end index. (Remember indexes start at 0!)<br><br>
For instance, `["hello", "my", "name", "is", "Bob"][2:4]` will return `["name", "is"]`

#### Exercise 4: Create a dictionary where the keys are the strings `'dictionary'`, `'list'`, and `'string'` and the values are numbers from 1-5 representing how comfortable you feel coding with each data type. Save it to a variable called `comfort_levels`
"""

# Your code here

comfort_levels = {'dictionary': 3, 'list' : 4, 'string': 5}

"""##### Hint:

Dictionaries are made up of key-value pairs. In this case the keys are the strings and the values paired with them are your ratings. See an example of the syntax below:<br>
```
my_dict = {key: value, key: value, key: value}
```

#### Exercise 5: Add together your ratings for lists and dictionaries by using the keys to access the values in the dictionary
"""

# Your code here

"""##### Hint:

You can access a value in the dictionary by using the key that corresponds with it.<br><br>For instance:
```
my_dict = {'pandas':'has its own data types'}
print(my_dict['pandas'])
```
will print "has its own data types"

#### Bonus: Write a loop that adds up all your confidence ratings. Then print the total
"""

# Your code here
total = 0
for key in comfort_levels:
  total += comfort_levels[key]

print(total)

"""##### Hint 1:

A for loop will iterate through all the items in a collection. When the collection is a dictionary, the "iterative variable" will store the keys as it loops through<br><br>
You can add to an existing variable with `+=`. For instance,
```
x = 10
x += 1
print(x)
```
will print `11`

##### Hint 2: Example of looping through a dictionary

Here is an example of the syntax for looping through a dictionary:
```
for key in my_dictionary:
  print(my_dictionary[key])
```
This code will print all the ***values*** stored in the dictionary
"""
